import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AsambleaResponseDto } from './dto/asamblea-response.dto';
import { CreateAsambleaDto } from './dto/create-asamblea.dto';
import { QueryAsambleasDto } from './dto/query-asambleas.dto';
import { UpdateAsambleaDto } from './dto/update-asamblea.dto';

@Injectable()
export class AsambleasService {
  constructor(private readonly prisma: PrismaService) {}
  async create(t: bigint, u: bigint, d: CreateAsambleaDto) { return this.ctx(u, t, async (tx) => this.toRes(await tx.asambleas.create({ data: { id_tenant: t, fecha_programada: this.dt(d.fechaProgramada,'fechaProgramada'), hora_inicio_real: this.odt(d.horaInicioReal,'horaInicioReal'), hora_fin_real: this.odt(d.horaFinReal,'horaFinReal'), tipo: d.tipo, convocatoria: this.on(d.convocatoria), estado: d.estado ?? 'PROGRAMADA', tema_principal: this.req(d.temaPrincipal,'temaPrincipal'), lugar: this.n(d.lugar), quorum_requerido: d.quorumRequerido ?? null, quorum_alcanzado: d.quorumAlcanzado ?? null, numero_acta: this.n(d.numeroActa), observaciones: this.n(d.observaciones) } }))); }
  async findAll(t: bigint, u: bigint, q: QueryAsambleasDto) { const from = q.from ? new Date(q.from) : undefined; const to = q.to ? new Date(q.to) : undefined; return this.ctx(u, t, async (tx) => (await tx.asambleas.findMany({ where: { id_tenant: t, tipo: q.tipo, convocatoria: q.convocatoria, estado: q.estado, fecha_programada: from || to ? { gte: from, lte: to } : undefined }, orderBy: { id_asamblea: 'desc' } })).map((i) => this.toRes(i))); }
  async findOne(t: bigint, u: bigint, id: bigint) { const i = await this.ctx(u, t, (tx) => tx.asambleas.findUnique({ where: { id_tenant_id_asamblea: { id_tenant: t, id_asamblea: id } } })); if (!i) throw new NotFoundException('No se encontro la asamblea solicitada.'); return this.toRes(i); }
  async update(t: bigint, u: bigint, id: bigint, d: UpdateAsambleaDto) { return this.ctx(u, t, async (tx) => { try { return this.toRes(await tx.asambleas.update({ where: { id_tenant_id_asamblea: { id_tenant: t, id_asamblea: id } }, data: { fecha_programada: d.fechaProgramada !== undefined ? this.dt(d.fechaProgramada,'fechaProgramada') : undefined, hora_inicio_real: d.horaInicioReal !== undefined ? this.odt(d.horaInicioReal,'horaInicioReal') : undefined, hora_fin_real: d.horaFinReal !== undefined ? this.odt(d.horaFinReal,'horaFinReal') : undefined, tipo: d.tipo, convocatoria: d.convocatoria !== undefined ? this.on(d.convocatoria) : undefined, estado: d.estado, tema_principal: d.temaPrincipal !== undefined ? this.req(d.temaPrincipal,'temaPrincipal') : undefined, lugar: this.on(d.lugar), quorum_requerido: d.quorumRequerido !== undefined ? d.quorumRequerido : undefined, quorum_alcanzado: d.quorumAlcanzado !== undefined ? d.quorumAlcanzado : undefined, numero_acta: d.numeroActa !== undefined ? this.n(d.numeroActa) : undefined, observaciones: this.on(d.observaciones) } })); } catch (e) { this.known(e,'No se encontro la asamblea solicitada.'); throw e; } }); }
  async remove(t: bigint, u: bigint, id: bigint) { await this.ctx(u, t, async (tx) => { try { await tx.asambleas.delete({ where: { id_tenant_id_asamblea: { id_tenant: t, id_asamblea: id } } }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2003') throw new ConflictException('No se puede eliminar la asamblea porque tiene relaciones asociadas.'); this.known(e,'No se encontro la asamblea solicitada.'); throw e; } }); }
  parseId(id: string) { if (!/^\d+$/.test(id)) throw new BadRequestException('idAsamblea debe ser un entero positivo.'); return BigInt(id); }
  private async ctx<T>(u: bigint, t: bigint, fn: (tx: Prisma.TransactionClient) => Promise<T>): Promise<T> { return this.prisma.$transaction(async (tx) => { await tx.$executeRaw(Prisma.sql`SELECT set_config('app.user_id', ${u.toString()}, true)`); await tx.$executeRaw(Prisma.sql`SELECT set_config('app.tenant_id', ${t.toString()}, true)`); const m = await tx.tenant_users.findFirst({ where: { id_tenant: t, id_user: u, estado: 'ACTIVO' }, select: { id_user: true } }); if (!m) throw new ForbiddenException('El usuario no pertenece al tenant activo.'); return fn(tx); }); }
  private req(v: string, f: string) { const n = v?.trim(); if (!n) throw new BadRequestException(`${f} es obligatorio.`); return n; }
  private n(v?: string | null) { if (v === undefined || v === null) return null; const n = v.trim(); return n || null; }
  private on(v?: string | null) { if (v === undefined) return undefined; return this.n(v); }
  private dt(v: string, f: string) { const d = new Date(v); if (Number.isNaN(d.getTime())) throw new BadRequestException(`${f} no tiene formato valido.`); return d; }
  private odt(v: string | null | undefined, f: string) { if (v === undefined || v === null) return null; return this.dt(v, f); }
  private known(e: unknown, m: string) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2025') throw new NotFoundException(m); }
  private toRes(i: { id_tenant: bigint; id_asamblea: bigint; fecha_programada: Date; hora_inicio_real: Date | null; hora_fin_real: Date | null; tipo: string; convocatoria: string | null; estado: string; tema_principal: string; lugar: string | null; quorum_requerido: number | null; quorum_alcanzado: number | null; numero_acta: string | null; observaciones: string | null; cerrada_at: Date | null; cerrada_by_user: bigint | null; }): AsambleaResponseDto {
    return { idTenant: Number(i.id_tenant), idAsamblea: Number(i.id_asamblea), fechaProgramada: i.fecha_programada, horaInicioReal: i.hora_inicio_real, horaFinReal: i.hora_fin_real, tipo: i.tipo, convocatoria: i.convocatoria, estado: i.estado, temaPrincipal: i.tema_principal, lugar: i.lugar, quorumRequerido: i.quorum_requerido, quorumAlcanzado: i.quorum_alcanzado, numeroActa: i.numero_acta, observaciones: i.observaciones, cerradaAt: i.cerrada_at, cerradaByUser: i.cerrada_by_user === null ? null : Number(i.cerrada_by_user) };
  }
}
