/*
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'juntascloudv3'
  AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS juntascloudv3;
CREATE DATABASE juntascloudv3;
 */
-- =========================================================
-- JUNTASCLOUD V3
-- PostgreSQL - multi-tenant SaaS
-- Base: una sola BD, múltiples asociaciones
-- =========================================================

CREATE EXTENSION IF NOT EXISTS citext;

-- =========================================================
-- HELPERS
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 0) MODULOS GLOBALES (mODULOS PERFILES)
-- =========================================================
CREATE TABLE app_modules (
  module_code VARCHAR(80) PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  grupo VARCHAR(100) NOT NULL,
  orden INT NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================================================
-- 0) USERS GLOBALES (LOGIN)
-- =========================================================
CREATE TABLE auth_users (
  id_user              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email                CITEXT NOT NULL,
  nombres              VARCHAR(100) NOT NULL,
  apellidos            VARCHAR(100) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  email_verified       BOOLEAN NOT NULL DEFAULT FALSE,
  email_verified_at    TIMESTAMPTZ NULL,
  last_login_at        TIMESTAMPTZ NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_auth_users PRIMARY KEY (id_user),
  CONSTRAINT ux_auth_users_email UNIQUE (email),
  CONSTRAINT ck_auth_users_estado CHECK (estado IN ('ACTIVO','INACTIVO','BLOQUEADO'))
);
CREATE INDEX inx_auth_users_estado ON auth_users (estado);

CREATE TRIGGER trg_auth_users_updated_at
BEFORE UPDATE ON auth_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TABLE auth_user_tokens (
  id_token             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_user              BIGINT NOT NULL,
  token_hash           VARCHAR(255) NOT NULL,
  token_type           VARCHAR(30) NOT NULL,
  expires_at           TIMESTAMPTZ NOT NULL,
  used_at              TIMESTAMPTZ NULL,
  revoked_at           TIMESTAMPTZ NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_ip           VARCHAR(45),
  user_agent           TEXT,

  CONSTRAINT pk_auth_user_tokens PRIMARY KEY (id_token),
  CONSTRAINT fk_auth_user_tokens_user FOREIGN KEY (id_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ux_auth_user_tokens_hash UNIQUE (token_hash),
  CONSTRAINT ck_auth_user_tokens_type CHECK (
    token_type IN ('VERIFY_EMAIL','RESET_PASSWORD','CHANGE_EMAIL')
  ),
  CONSTRAINT ck_auth_user_tokens_dates CHECK (expires_at > created_at)
);
CREATE INDEX inx_auth_user_tokens_user ON auth_user_tokens (id_user);
CREATE INDEX inx_auth_user_tokens_user_type ON auth_user_tokens (id_user, token_type);
CREATE INDEX inx_auth_user_tokens_expires ON auth_user_tokens (expires_at);



CREATE TABLE auth_login_logs (
  id_log               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user              BIGINT NULL, -- null si fue intento fallido con email inexistente
  email                CITEXT NOT NULL,
  login_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  success              BOOLEAN NOT NULL,
  ip_address           VARCHAR(45),
  user_agent           TEXT,
  failure_reason       VARCHAR(100),

  CONSTRAINT fk_login_user FOREIGN KEY (id_user)
    REFERENCES auth_users(id_user)
);
CREATE INDEX inx_login_logs_user ON auth_login_logs (id_user);
CREATE INDEX inx_login_logs_date ON auth_login_logs (login_at);
CREATE INDEX inx_login_logs_success ON auth_login_logs (success);


-- =========================================================
-- 1) TENANTS
-- =========================================================
CREATE TABLE tenants (
  id_tenant            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre               VARCHAR(150) NOT NULL,
  tipo_documento       VARCHAR(15) NULL,
  numero_documento     VARCHAR(20) NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  observaciones        VARCHAR(300),
  owner_user_id        BIGINT NOT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenants PRIMARY KEY (id_tenant),
  CONSTRAINT fk_tenants_owner FOREIGN KEY (owner_user_id) REFERENCES auth_users(id_user),
  CONSTRAINT ux_tenants_nombre UNIQUE (owner_user_id, nombre),
  CONSTRAINT ck_tenants_estado CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO')),
  CONSTRAINT ck_tenants_tipo_documento CHECK (
    tipo_documento IS NULL OR tipo_documento IN ('RUC','DNI','OTRO')
  )
);
CREATE INDEX inx_tenants_estado ON tenants (estado);

CREATE TRIGGER trg_tenants_updated_at
BEFORE UPDATE ON tenants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 1.1) PERFILES tenant_PERFILES
-- =========================================================
CREATE TABLE tenant_profiles (
  id_tenant BIGINT NOT NULL,
  id_profile BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_tenant_profiles PRIMARY KEY (id_tenant, id_profile),
  CONSTRAINT fk_profiles_tenant FOREIGN KEY (id_tenant)
    REFERENCES tenants(id_tenant),
  CONSTRAINT ux_profiles_nombre UNIQUE (id_tenant, nombre)
);

CREATE TABLE tenant_profile_modules (
  id_tenant BIGINT NOT NULL,
  id_profile BIGINT NOT NULL,
  module_code VARCHAR(80) NOT NULL,
  access_level VARCHAR(20) NOT NULL DEFAULT 'SIN_ACCESO',

  CONSTRAINT pk_tenant_profile_modules
    PRIMARY KEY (id_tenant, id_profile, module_code),

  CONSTRAINT fk_tpm_profile
    FOREIGN KEY (id_tenant, id_profile)
    REFERENCES tenant_profiles(id_tenant, id_profile),

  CONSTRAINT fk_tpm_module
    FOREIGN KEY (module_code)
    REFERENCES app_modules(module_code),

  CONSTRAINT ck_tpm_access_level CHECK (
    access_level IN ('SIN_ACCESO','SOLO_LECTURA','ACCESO_TOTAL')
  )
);


-- =========================================================
-- 2) MEMBRESÍAS tenant_users
-- =========================================================
CREATE TABLE tenant_users (
  id_tenant            BIGINT NOT NULL,
  id_user              BIGINT NOT NULL,
  role                 VARCHAR(15) NOT NULL DEFAULT 'MEMBER',
  estado               VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  joined_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at          TIMESTAMPTZ NULL,
  ended_at             TIMESTAMPTZ NULL,
  invited_by           BIGINT NULL,
  id_persona           BIGINT NULL,-- opcional: vincular a una persona del padrón de ESA junta
  id_profile           BIGINT NULL, -- PERFIL

  CONSTRAINT pk_tenant_users PRIMARY KEY (id_tenant, id_user),
  CONSTRAINT fk_tu_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_tu_user FOREIGN KEY (id_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_tu_invited FOREIGN KEY (invited_by) REFERENCES auth_users(id_user),
  -- CONSTRAINT fk_tenant_users_profile FOREIGN KEY (id_tenant, id_profile) REFERENCES tenant_profiles(id_tenant, id_profile),

  CONSTRAINT ck_tu_role CHECK (role IN ('OWNER','ADMIN','MEMBER')),
  CONSTRAINT ck_tu_estado CHECK (estado IN ('PENDIENTE','ACTIVO','INACTIVO','RECHAZADO')),
  CONSTRAINT ck_tu_ended CHECK (ended_at IS NULL OR ended_at >= joined_at)
);

CREATE INDEX inx_tenant_users_user ON tenant_users (id_user);
CREATE INDEX inx_tenant_users_tenant_role_estado ON tenant_users (id_tenant, role, estado);

CREATE UNIQUE INDEX ux_one_owner_per_tenant
ON tenant_users (id_tenant)
WHERE role = 'OWNER' AND estado = 'ACTIVO';


-- =========================================================
-- 3) INVITACIONES (recomendado para "compartir")
-- =========================================================

CREATE TABLE tenant_invitations (
  id_invitation        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,-- A qué junta pertenece la invitación.
  email                CITEXT NOT NULL,--A qué correo se está invitando.(No necesitas que el usuario exista aún.)
  role                 VARCHAR(15) NOT NULL DEFAULT 'MEMBER',--Qué rol tendrá si acepta.
  token_hash           VARCHAR(255) NOT NULL,--Token único para aceptar la invitación.
  status               VARCHAR(15) NOT NULL DEFAULT 'PENDING',--Estado actual de la invitación.
  expires_at           TIMESTAMPTZ NOT NULL,--Fecha límite para aceptar.
  accepted_at          TIMESTAMPTZ NULL,--Cuándo se aceptó la invitación.
  revoked_at           TIMESTAMPTZ NULL,--Cuándo se rechazo la invitación.
  invited_by           BIGINT NOT NULL,--Qué usuario hizo la invitación.
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),--Cuándo se creó la invitación.

  CONSTRAINT pk_tenant_invitations PRIMARY KEY (id_invitation),
  CONSTRAINT fk_inv_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_inv_user FOREIGN KEY (invited_by) REFERENCES auth_users(id_user),

  CONSTRAINT ux_inv_token_hash UNIQUE (token_hash),
  CONSTRAINT ck_inv_role CHECK (role IN ('ADMIN','MEMBER')),
  CONSTRAINT ck_inv_status CHECK (status IN ('PENDING','ACCEPTED','REVOKED','EXPIRED')),
  CONSTRAINT ck_inv_dates CHECK (expires_at > created_at)
);

CREATE INDEX inx_inv_tenant ON tenant_invitations (id_tenant);
CREATE INDEX inx_inv_email ON tenant_invitations (email);
CREATE INDEX inx_inv_status ON tenant_invitations (status);

CREATE UNIQUE INDEX ux_inv_pending_per_email
ON tenant_invitations (id_tenant, email)
WHERE status = 'PENDING';





-- =========================================================
-- 4) PERSONAS
-- =========================================================
CREATE TABLE personas (
  id_tenant            BIGINT NOT NULL,
  id_persona           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  nombres              VARCHAR(100) NOT NULL,
  apellido_paterno     VARCHAR(100) NOT NULL,
  apellido_materno     VARCHAR(100) NOT NULL,
  dni                  VARCHAR(15),
  email                CITEXT NULL,
  telefono             VARCHAR(20),
  direccion            VARCHAR(200),
  referencia_vivienda  VARCHAR(200),

  tipo_participante    VARCHAR(20) NOT NULL DEFAULT 'NO_PADRONADO',
  estado               VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

  fecha_registro       DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_baja           DATE NULL,
  observaciones        TEXT,

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_personas PRIMARY KEY (id_tenant, id_persona),
  CONSTRAINT fk_personas_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_personas_tipo CHECK (tipo_participante IN ('PADRONADO','NO_PADRONADO','INVITADO')),
  CONSTRAINT ck_personas_estado CHECK (estado IN ('ACTIVO','SUSPENDIDO','RETIRADO','FALLECIDO')),
  CONSTRAINT ck_personas_baja CHECK (fecha_baja IS NULL OR fecha_baja >= fecha_registro)
);

CREATE INDEX inx_personas_tenant ON personas (id_tenant);
CREATE INDEX inx_personas_nombre ON personas (id_tenant, apellido_paterno, apellido_materno, nombres);

CREATE UNIQUE INDEX ux_personas_dni
    ON personas (id_tenant, dni)
    WHERE dni IS NOT NULL;

CREATE UNIQUE INDEX ux_tenant_users_persona
ON tenant_users (id_tenant, id_persona)
WHERE id_persona IS NOT NULL;


CREATE TRIGGER trg_personas_updated_at
BEFORE UPDATE ON personas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


/*historial de cambios de condicion en persona para llevar un historial de los cambios*/
CREATE TABLE persona_condiciones (
  id_tenant            BIGINT NOT NULL,
  id_persona_condicion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona           BIGINT NOT NULL,
  condicion            VARCHAR(20) NOT NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE NULL,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_persona_condiciones PRIMARY KEY (id_tenant, id_persona_condicion),
  CONSTRAINT fk_pc_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_pc_user FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_pc_condicion CHECK (
    condicion IN ('PADRONADO','NO_PADRONADO','INVITADO','SUSPENDIDO','RETIRADO','FALLECIDO')
  ),
  CONSTRAINT ck_pc_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

-- =========================================================
-- 5) TERRENOS / BIENES
-- =========================================================
CREATE TABLE terrenos (
  id_tenant            BIGINT NOT NULL,
  id_terreno           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  codigo_lote          VARCHAR(30),
  manzana              VARCHAR(20),
  numero_lote          VARCHAR(20),
  descripcion          VARCHAR(200) NOT NULL,
  area_aprox_m2        NUMERIC(10,2),
  area_legal_m2        NUMERIC(10,2),
  partida_registral    VARCHAR(50),
  ubicacion            VARCHAR(200),
  estado               VARCHAR(20) NOT NULL DEFAULT 'EN_USO',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_terrenos PRIMARY KEY (id_tenant, id_terreno),
  CONSTRAINT fk_terrenos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_terrenos_estado CHECK (
    estado IN ('EN_USO','EN_VENTA','VENDIDO_PARCIAL','VENDIDO_TOTAL','RESERVA')
  )
);
CREATE INDEX inx_terrenos_estado ON terrenos (id_tenant, estado);

CREATE TRIGGER trg_terrenos_updated_at
BEFORE UPDATE ON terrenos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
--  TABLA: bienes
-- =========================================================
CREATE TABLE bienes (
  id_tenant            BIGINT NOT NULL,
  id_bien              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  descripcion          VARCHAR(200) NOT NULL,
  tipo                 VARCHAR(50),
  cantidad             INT NOT NULL,
  valor_estimado       NUMERIC(10,2),
  ubicacion            VARCHAR(200),
  fecha_alta           DATE NOT NULL,
  fecha_baja           DATE,
  estado               VARCHAR(20) NOT NULL DEFAULT 'BUENO',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_bienes PRIMARY KEY (id_tenant, id_bien),
  CONSTRAINT fk_bienes_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_bienes_estado CHECK (estado IN ('BUENO','REGULAR','MALO','DADO_DE_BAJA'))
);
CREATE INDEX inx_bienes_estado ON bienes (id_tenant, estado);
CREATE INDEX inx_bienes_tipo ON bienes (id_tenant, tipo);

CREATE TRIGGER trg_bienes_updated_at
BEFORE UPDATE ON bienes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
--  TABLA: persona_terreno (M:N)
-- =========================================================
CREATE TABLE persona_terreno (
  id_tenant                 BIGINT NOT NULL,
  id_persona_terreno        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona                BIGINT NOT NULL,
  id_terreno                BIGINT NOT NULL,
  tipo_relacion             VARCHAR(15) NOT NULL,
  porcentaje_participacion  NUMERIC(5,2),

  CONSTRAINT pk_persona_terreno PRIMARY KEY (id_tenant, id_persona_terreno),
  CONSTRAINT fk_pt_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_pt_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_pt_terreno FOREIGN KEY (id_tenant, id_terreno)
    REFERENCES terrenos (id_tenant, id_terreno),
  CONSTRAINT ux_persona_terreno UNIQUE (id_tenant, id_persona, id_terreno),
  CONSTRAINT ck_persona_terreno_tipo CHECK (
    tipo_relacion IN ('PROPIETARIO','POSEEDOR','COPROPIETARIO','FAMILIAR','OTRO')
  )
);



-- =========================================================
-- 6) GOBIERNO DE LA JUNTA
-- =========================================================
-- =========================================================
--  TABLA: juntas_directivas
-- =========================================================
CREATE TABLE juntas_directivas (
  id_tenant            BIGINT NOT NULL,
  id_junta             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  fecha_eleccion       DATE NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'VIGENTE',
  documento_sustento   VARCHAR(100),
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_juntas_directivas PRIMARY KEY (id_tenant, id_junta),
  CONSTRAINT fk_jd_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_jd_estado CHECK (estado IN ('VIGENTE','CESADA','ANULADA','PROYECTADA')),
  CONSTRAINT ck_jd_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX inx_juntas_directivas_estado ON juntas_directivas (id_tenant, estado);

CREATE UNIQUE INDEX ux_junta_vigente
ON juntas_directivas (id_tenant)
WHERE estado = 'VIGENTE';

CREATE TRIGGER trg_juntas_directivas_updated_at
BEFORE UPDATE ON juntas_directivas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
--  TABLA: junta_miembros
-- =========================================================
CREATE TABLE junta_miembros (
  id_tenant            BIGINT NOT NULL,
  id_junta_miembro     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_junta             BIGINT NOT NULL,
  id_persona           BIGINT NOT NULL,
  cargo                VARCHAR(20) NOT NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_junta_miembros PRIMARY KEY (id_tenant, id_junta_miembro),
  CONSTRAINT fk_jm_junta FOREIGN KEY (id_tenant, id_junta)
    REFERENCES juntas_directivas (id_tenant, id_junta),
  CONSTRAINT fk_jm_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT ck_jm_cargo CHECK (
    cargo IN ('PRESIDENTE','VICEPRESIDENTE','SECRETARIO','TESORERO','VOCAL','OTRO')
  ),
  CONSTRAINT ck_jm_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX inx_junta_miembros_junta ON junta_miembros (id_tenant, id_junta);
CREATE INDEX inx_junta_miembros_persona ON junta_miembros (id_tenant, id_persona);

CREATE UNIQUE INDEX ux_junta_presidente_activo
ON junta_miembros (id_tenant, id_junta, cargo)
WHERE cargo = 'PRESIDENTE' AND fecha_fin IS NULL;

CREATE TRIGGER trg_junta_miembros_updated_at
BEFORE UPDATE ON junta_miembros
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE TABLE asambleas (
  id_tenant            BIGINT NOT NULL,
  id_asamblea          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fecha_programada     TIMESTAMPTZ NOT NULL,
  hora_inicio_real     TIMESTAMPTZ NULL,
  hora_fin_real        TIMESTAMPTZ NULL,
  tipo                 VARCHAR(15) NOT NULL,
  convocatoria         VARCHAR(15) NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'PROGRAMADA',
  tema_principal       VARCHAR(200) NOT NULL,
  lugar                VARCHAR(200),
  quorum_requerido     INT,
  quorum_alcanzado     INT NULL,
  numero_acta          VARCHAR(50),
  observaciones        TEXT,
  cerrada_at           TIMESTAMPTZ NULL,
  cerrada_by_user      BIGINT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_asambleas PRIMARY KEY (id_tenant, id_asamblea),
  CONSTRAINT fk_asambleas_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_asambleas_cerrada_by FOREIGN KEY (cerrada_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_asambleas_tipo CHECK (tipo IN ('ORDINARIA','EXTRAORDINARIA')),
  CONSTRAINT ck_asambleas_convocatoria CHECK (
    convocatoria IS NULL OR convocatoria IN ('PRIMERA','SEGUNDA')
  ),
  CONSTRAINT ck_asambleas_estado CHECK (
    estado IN ('PROGRAMADA','REALIZADA','CANCELADA','CERRADA')
  )
);
CREATE INDEX inx_asambleas_fecha ON asambleas (id_tenant, fecha_programada);

CREATE TRIGGER trg_asambleas_updated_at
BEFORE UPDATE ON asambleas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
--  TABLA: asistencia_asamblea (mejorada)
-- =========================================================
CREATE TABLE asistencia_asamblea (
  id_tenant                 BIGINT NOT NULL,
  id_asistencia             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_asamblea               BIGINT NOT NULL,
  id_persona                BIGINT NOT NULL,
  estado                    VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada              TIME,
  es_padronado_en_momento   BOOLEAN NOT NULL,
  tiene_derecho_voto        BOOLEAN NOT NULL DEFAULT FALSE,
  voto_emitido              BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones             TEXT,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user           BIGINT NOT NULL,
  updated_at                TIMESTAMPTZ NULL,
  updated_by_user           BIGINT NULL,

  anulado                   BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at                TIMESTAMPTZ NULL,
  anulado_by_user           BIGINT NULL,
  motivo_anulacion          TEXT NULL,

  CONSTRAINT pk_asistencia_asamblea PRIMARY KEY (id_tenant, id_asistencia),
  CONSTRAINT fk_aa_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_aa_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_aa_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT ux_asistencia_asamblea UNIQUE (id_tenant, id_asamblea, id_persona),
  CONSTRAINT ck_asistencia_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),
  CONSTRAINT ck_asistencia_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),
  CONSTRAINT fk_aa_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_aa_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_aa_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES auth_users(id_user)
);
CREATE INDEX inx_asistencia_asamblea_asamblea ON asistencia_asamblea (id_tenant, id_asamblea);
CREATE INDEX inx_asistencia_asamblea_persona ON asistencia_asamblea (id_tenant, id_persona);
CREATE INDEX inx_asistencia_asamblea_estado ON asistencia_asamblea (id_tenant, estado);



-- =========================================================
-- 7) FAENAS
-- =========================================================
CREATE TABLE faenas (
  id_tenant            BIGINT NOT NULL,
  id_faena             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fecha_programada     DATE NOT NULL,
  hora_inicio          TIME NULL,
  hora_fin             TIME NULL,
  descripcion          VARCHAR(200) NOT NULL,
  lugar                VARCHAR(200),
  tipo_faena           VARCHAR(20) NOT NULL DEFAULT 'ORDINARIA',
  es_obligatoria       BOOLEAN NOT NULL DEFAULT TRUE,
  estado               VARCHAR(15) NOT NULL DEFAULT 'PROGRAMADA',
  monto_multa_base     NUMERIC(10,2) NULL,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_faenas PRIMARY KEY (id_tenant, id_faena),
  CONSTRAINT fk_faenas_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_faena_tipo CHECK (tipo_faena IN ('ORDINARIA','EXTRAORDINARIA','RECUPERACION')),
  CONSTRAINT ck_faena_estado CHECK (estado IN ('PROGRAMADA','EJECUTADA','CANCELADA'))
);
CREATE INDEX inx_faenas_fecha ON faenas (id_tenant, fecha_programada);

CREATE TRIGGER trg_faenas_updated_at
BEFORE UPDATE ON faenas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- =========================================================
--  TABLA: faena_participacion
-- =========================================================
CREATE TABLE faena_participacion (
  id_tenant                 BIGINT NOT NULL,
  id_faena_participacion    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_faena                  BIGINT NOT NULL,
  id_persona                BIGINT NOT NULL,
  estado                    VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada              TIME,
  cant_personas_extra       SMALLINT NOT NULL DEFAULT 0,
  multa_generada            BOOLEAN NOT NULL DEFAULT FALSE,
  monto_multa               NUMERIC(10,2),
  observaciones             TEXT,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user           BIGINT NOT NULL,
  updated_at                TIMESTAMPTZ NULL,
  updated_by_user           BIGINT NULL,

  anulado                   BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at                TIMESTAMPTZ NULL,
  anulado_by_user           BIGINT NULL,
  motivo_anulacion          TEXT NULL,

  CONSTRAINT pk_faena_participacion PRIMARY KEY (id_tenant, id_faena_participacion),
  CONSTRAINT fk_fp_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_fp_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_fp_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT ux_faena_participacion UNIQUE (id_tenant, id_faena, id_persona),

  CONSTRAINT ck_fp_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),
  CONSTRAINT ck_fp_multa CHECK (
    (multa_generada = FALSE AND monto_multa IS NULL)
    OR
    (multa_generada = TRUE AND monto_multa IS NOT NULL AND monto_multa >= 0)
  ),
  CONSTRAINT ck_fp_extra CHECK (
    cant_personas_extra >= 0 AND cant_personas_extra <= 20
  ),
  CONSTRAINT ck_fp_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),
  CONSTRAINT fk_fp_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_fp_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_fp_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES auth_users(id_user)
);

CREATE INDEX inx_fp_faena ON faena_participacion (id_tenant, id_faena);
CREATE INDEX inx_fp_persona ON faena_participacion (id_tenant, id_persona);
CREATE INDEX inx_fp_estado ON faena_participacion (id_tenant, estado);



-- =========================================================
-- 8) CAJA
-- =========================================================
-- =========================================================
--  TABLA: caja_movimientos (FINAL: auditoría + anulación)
-- =========================================================
CREATE TABLE caja_categorias (
  id_tenant            BIGINT NOT NULL,
  id_categoria_caja    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  tipo                 VARCHAR(10) NOT NULL,
  activo               BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_caja_categorias PRIMARY KEY (id_tenant, id_categoria_caja),
  CONSTRAINT fk_ccat_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_ccat_tipo CHECK (tipo IN ('INGRESO','GASTO'))
);

CREATE TABLE caja_movimientos (
  id_tenant            BIGINT NOT NULL,
  id_movimiento        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  fecha                DATE NOT NULL,
  tipo                 VARCHAR(10) NOT NULL,
  monto                NUMERIC(10,2) NOT NULL,
  id_categoria_caja    BIGINT NOT NULL,

  id_persona           BIGINT NULL,
  id_faena             BIGINT NULL,
  id_asamblea          BIGINT NULL,
  id_bien              BIGINT NULL,

  id_user              BIGINT NOT NULL,
  descripcion          VARCHAR(255),
  medio_pago           VARCHAR(20) NOT NULL,
  doc_referencia       VARCHAR(100),
  observaciones        TEXT,

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,
  updated_at           TIMESTAMPTZ NULL,
  updated_by_user      BIGINT NULL,

  anulado              BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at           TIMESTAMPTZ NULL,
  anulado_by_user      BIGINT NULL,
  motivo_anulacion     TEXT NULL,

  CONSTRAINT pk_caja_movimientos PRIMARY KEY (id_tenant, id_movimiento),
  CONSTRAINT fk_cm_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_cm_categoria FOREIGN KEY (id_tenant, id_categoria_caja)
    REFERENCES caja_categorias (id_tenant, id_categoria_caja),
  CONSTRAINT fk_cm_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_cm_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_cm_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_cm_bien FOREIGN KEY (id_tenant, id_bien)
    REFERENCES bienes (id_tenant, id_bien),
  CONSTRAINT fk_cm_user FOREIGN KEY (id_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES auth_users(id_user),

  CONSTRAINT ck_cm_tipo CHECK (tipo IN ('INGRESO','GASTO')),
  CONSTRAINT ck_cm_monto CHECK (monto > 0),
  CONSTRAINT ck_cm_medio_pago CHECK (
    medio_pago IN ('EFECTIVO','TRANSFERENCIA','YAPE','PLIN','OTRO')
  ),
  CONSTRAINT ck_cm_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  )
);

CREATE INDEX inx_cm_fecha_tipo ON caja_movimientos (id_tenant, fecha, tipo);
CREATE INDEX inx_cm_persona ON caja_movimientos (id_tenant, id_persona);
CREATE INDEX inx_cm_user ON caja_movimientos (id_tenant, id_user);



-- =========================================================
-- 9) OBLIGACIONES / COBRANZA
-- =========================================================
CREATE TABLE conceptos_cobro (
  id_tenant            BIGINT NOT NULL,
  id_concepto_cobro    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  tipo                 VARCHAR(25) NOT NULL,
  activo               BOOLEAN NOT NULL DEFAULT TRUE,
  requiere_periodo     BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones        TEXT,

  CONSTRAINT pk_conceptos_cobro PRIMARY KEY (id_tenant, id_concepto_cobro),
  CONSTRAINT fk_conceptos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_conceptos_tipo CHECK (
    tipo IN ('CUOTA_ORDINARIA','CUOTA_EXTRAORDINARIA','MULTA_FAENA','MULTA_ASAMBLEA','APORTE','OTRO')
  )
);

CREATE TABLE obligaciones_persona (
  id_tenant            BIGINT NOT NULL,
  id_obligacion        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona           BIGINT NOT NULL,
  id_concepto_cobro    BIGINT NOT NULL,
  periodo              VARCHAR(20) NULL,
  fecha_emision        DATE NOT NULL,
  fecha_vencimiento    DATE NULL,

  monto_original       NUMERIC(10,2) NOT NULL,
  monto_pagado         NUMERIC(10,2) NOT NULL DEFAULT 0,
  monto_exonerado      NUMERIC(10,2) NOT NULL DEFAULT 0,
  monto_compensado     NUMERIC(10,2) NOT NULL DEFAULT 0,
  saldo                NUMERIC(10,2) NOT NULL,
  estado               VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',

  id_faena             BIGINT NULL,
  id_asamblea          BIGINT NULL,

  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,
  updated_at           TIMESTAMPTZ NULL,
  updated_by_user      BIGINT NULL,

  anulada_at           TIMESTAMPTZ NULL,
  anulada_by_user      BIGINT NULL,
  motivo_anulacion     TEXT NULL,

  CONSTRAINT pk_obligaciones_persona PRIMARY KEY (id_tenant, id_obligacion),
  CONSTRAINT fk_op_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_op_concepto FOREIGN KEY (id_tenant, id_concepto_cobro)
    REFERENCES conceptos_cobro (id_tenant, id_concepto_cobro),
  CONSTRAINT fk_op_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_op_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_op_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_op_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_op_anulada_by FOREIGN KEY (anulada_by_user) REFERENCES auth_users(id_user),

  CONSTRAINT ck_op_montos CHECK (
    monto_original >= 0 AND monto_pagado >= 0 AND monto_exonerado >= 0
    AND monto_compensado >= 0 AND saldo >= 0
  ),
  CONSTRAINT ck_op_estado CHECK (
    estado IN ('PENDIENTE','PARCIAL','PAGADA','EXONERADA','COMPENSADA','ANULADA')
  )
);

CREATE INDEX inx_obligaciones_persona_persona ON obligaciones_persona (id_tenant, id_persona);
CREATE INDEX inx_obligaciones_persona_estado ON obligaciones_persona (id_tenant, estado);



CREATE TABLE obligacion_pagos (
  id_tenant            BIGINT NOT NULL,
  id_obligacion_pago   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_obligacion        BIGINT NOT NULL,
  id_movimiento        BIGINT NOT NULL,
  monto_aplicado       NUMERIC(10,2) NOT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_obligacion_pagos PRIMARY KEY (id_tenant, id_obligacion_pago),
  CONSTRAINT fk_obp_obligacion FOREIGN KEY (id_tenant, id_obligacion)
    REFERENCES obligaciones_persona (id_tenant, id_obligacion),
  CONSTRAINT fk_obp_movimiento FOREIGN KEY (id_tenant, id_movimiento)
    REFERENCES caja_movimientos (id_tenant, id_movimiento),
  CONSTRAINT fk_obp_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_obp_monto CHECK (monto_aplicado > 0)
);

CREATE TABLE obligacion_movimientos (
  id_tenant                 BIGINT NOT NULL,
  id_obligacion_movimiento  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_obligacion             BIGINT NOT NULL,
  tipo_movimiento           VARCHAR(20) NOT NULL,
  monto                     NUMERIC(10,2) NOT NULL,
  fecha_movimiento          TIMESTAMPTZ NOT NULL DEFAULT now(),
  referencia_tipo           VARCHAR(30) NULL,
  referencia_id             BIGINT NULL,
  observaciones             TEXT,
  created_by_user           BIGINT NOT NULL,

  CONSTRAINT pk_obligacion_movimientos PRIMARY KEY (id_tenant, id_obligacion_movimiento),
  CONSTRAINT fk_om_obligacion FOREIGN KEY (id_tenant, id_obligacion)
    REFERENCES obligaciones_persona (id_tenant, id_obligacion),
  CONSTRAINT fk_om_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_om_tipo CHECK (
    tipo_movimiento IN (
      'CREACION','PAGO','EXONERACION','AJUSTE_POSITIVO',
      'AJUSTE_NEGATIVO','ANULACION','COMPENSACION'
    )
  ),
  CONSTRAINT ck_om_monto CHECK (monto >= 0)
);



-- =========================================================
-- 10) CRÉDITOS POR FAENAS ADELANTADAS
-- =========================================================
CREATE TABLE creditos_persona (
  id_tenant            BIGINT NOT NULL,
  id_credito           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_persona           BIGINT NOT NULL,
  tipo_credito         VARCHAR(20) NOT NULL,
  cantidad_original    NUMERIC(10,2) NOT NULL,
  cantidad_disponible  NUMERIC(10,2) NOT NULL,
  equivalencia_monto   NUMERIC(10,2) NULL,
  referencia_tipo      VARCHAR(30) NULL,
  referencia_id        BIGINT NULL,
  fecha_generacion     TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_vencimiento    TIMESTAMPTZ NULL,
  estado               VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_creditos_persona PRIMARY KEY (id_tenant, id_credito),
  CONSTRAINT fk_cp_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_cp_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_cp_tipo CHECK (tipo_credito IN ('FAENA_ADELANTADA','BONIFICACION','OTRO')),
  CONSTRAINT ck_cp_estado CHECK (estado IN ('DISPONIBLE','CONSUMIDO','VENCIDO','ANULADO')),
  CONSTRAINT ck_cp_cantidades CHECK (
    cantidad_original > 0 AND cantidad_disponible >= 0
    AND cantidad_disponible <= cantidad_original
  )
);

CREATE TABLE credito_movimientos (
  id_tenant               BIGINT NOT NULL,
  id_credito_movimiento   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_credito              BIGINT NOT NULL,
  tipo_movimiento         VARCHAR(20) NOT NULL,
  cantidad                NUMERIC(10,2) NOT NULL,
  fecha_movimiento        TIMESTAMPTZ NOT NULL DEFAULT now(),
  referencia_tipo         VARCHAR(30) NULL,
  referencia_id           BIGINT NULL,
  observaciones           TEXT,
  created_by_user         BIGINT NOT NULL,

  CONSTRAINT pk_credito_movimientos PRIMARY KEY (id_tenant, id_credito_movimiento),
  CONSTRAINT fk_crm_credito FOREIGN KEY (id_tenant, id_credito)
    REFERENCES creditos_persona (id_tenant, id_credito),
  CONSTRAINT fk_crm_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_crm_tipo CHECK (
    tipo_movimiento IN ('GENERACION','CONSUMO','AJUSTE','VENCIMIENTO','ANULACION')
  ),
  CONSTRAINT ck_crm_cantidad CHECK (cantidad > 0)
);

-- =========================================================
-- 11) DOCUMENTOS / AUDITORIA
-- =========================================================
CREATE TABLE documentos (
  id_tenant            BIGINT NOT NULL,
  id_documento         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  modulo               VARCHAR(30) NOT NULL,
  entidad_id           BIGINT NOT NULL,
  nombre_archivo       VARCHAR(255) NOT NULL,
  nombre_original      VARCHAR(255) NOT NULL,
  mime_type            VARCHAR(100) NOT NULL,
  tamano_bytes         BIGINT NOT NULL,
  storage_path         VARCHAR(500) NOT NULL,
  uploaded_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  uploaded_by_user     BIGINT NOT NULL,
  observaciones        TEXT,

  CONSTRAINT pk_documentos PRIMARY KEY (id_tenant, id_documento),
  CONSTRAINT fk_documentos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_documentos_user FOREIGN KEY (uploaded_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_documentos_modulo CHECK (
    modulo IN ('PERSONA','TERRENO','ASAMBLEA','FAENA','BIEN','CAJA','JUNTA_DIRECTIVA')
  )
);

CREATE TABLE audit_log (
  id_audit             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tenant            BIGINT NULL,
  table_name           VARCHAR(100) NOT NULL,
  record_pk            VARCHAR(200) NOT NULL,
  action               VARCHAR(10) NOT NULL,
  old_data             JSONB NULL,
  new_data             JSONB NULL,
  changed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  changed_by_user      BIGINT NULL,
  ip_address           VARCHAR(45),

  CONSTRAINT fk_audit_user FOREIGN KEY (changed_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_audit_action CHECK (
    action IN ('INSERT','UPDATE','DELETE','ANULACION')
  )
);



-- =========================================================
-- CATÁLOGOS BASE / PLANTILLAS GLOBALES
-- =========================================================

CREATE TABLE conceptos_cobro_base (
  id_concepto_cobro_base BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre                 VARCHAR(100) NOT NULL,
  tipo                   VARCHAR(25) NOT NULL,
  activo                 BOOLEAN NOT NULL DEFAULT TRUE,
  requiere_periodo       BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones          TEXT,

  CONSTRAINT pk_conceptos_cobro_base PRIMARY KEY (id_concepto_cobro_base),
  CONSTRAINT ux_conceptos_cobro_base_tipo UNIQUE (tipo),
  CONSTRAINT ck_conceptos_cobro_base_tipo CHECK (
    tipo IN ('CUOTA_ORDINARIA','CUOTA_EXTRAORDINARIA','MULTA_FAENA','MULTA_ASAMBLEA','APORTE','OTRO')
  )
);


CREATE TABLE caja_categorias_base (
  id_categoria_caja_base BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre                 VARCHAR(100) NOT NULL,
  tipo                   VARCHAR(10) NOT NULL,
  activo                 BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_caja_categorias_base PRIMARY KEY (id_categoria_caja_base),
  CONSTRAINT ux_caja_categorias_base_nombre_tipo UNIQUE (nombre, tipo),
  CONSTRAINT ck_caja_categorias_base_tipo CHECK (
    tipo IN ('INGRESO','GASTO')
  )
);


-- 12) RLS
-- =========================================================

-- Tenants
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;

-- A) Ver tenants donde soy miembro activo
CREATE POLICY tenants_select_by_membership
ON tenants
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM tenant_users tu
    WHERE tu.id_tenant = tenants.id_tenant
      AND tu.id_user = current_setting('app.user_id')::bigint
      AND tu.estado = 'ACTIVO'
  )
);

-- B) Ver tenants donde soy owner (útil para recién creado)
CREATE POLICY tenants_select_by_owner
ON tenants
FOR SELECT
USING (
  owner_user_id = current_setting('app.user_id')::bigint
);

-- C) Permitir INSERT solo si el owner es el usuario actual
CREATE POLICY tenants_insert_by_owner
ON tenants
FOR INSERT
WITH CHECK (
  owner_user_id = current_setting('app.user_id')::bigint
);

-- (Opcional) Permitir UPDATE solo al owner
CREATE POLICY tenants_update_by_owner
ON tenants
FOR UPDATE
USING (
  owner_user_id = current_setting('app.user_id')::bigint
)
WITH CHECK (
  owner_user_id = current_setting('app.user_id')::bigint
);
-- DELETE
CREATE POLICY tenants_delete_by_owner
ON tenants
FOR DELETE
USING (
  owner_user_id = current_setting('app.user_id')::bigint
);



-- Tenant users
-- 5.2) Tenant_users: un usuario puede ver solo sus memberships
ALTER TABLE tenant_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_users_self_policy
ON tenant_users
USING (
  id_user = current_setting('app.user_id')::bigint
)
WITH CHECK (
  id_user = current_setting('app.user_id')::bigint
);

-- =========================================================
-- Helper de patrón RLS:
-- usar en tablas tenant-scoped:
-- id_tenant = app.tenant_id
-- y además el user debe pertenecer al tenant activo
-- =========================================================

ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
CREATE POLICY personas_policy ON personas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1
    FROM tenant_users tu
    WHERE tu.id_tenant = personas.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
);

ALTER TABLE terrenos ENABLE ROW LEVEL SECURITY;
CREATE POLICY terrenos_policy ON terrenos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = terrenos.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE juntas_directivas ENABLE ROW LEVEL SECURITY;
CREATE POLICY juntas_directivas_policy ON juntas_directivas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = juntas_directivas.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE faenas ENABLE ROW LEVEL SECURITY;
CREATE POLICY faenas_policy ON faenas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = faenas.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE asambleas ENABLE ROW LEVEL SECURITY;
CREATE POLICY asambleas_policy ON asambleas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = asambleas.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE bienes ENABLE ROW LEVEL SECURITY;
CREATE POLICY bienes_policy ON bienes
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = bienes.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE persona_terreno ENABLE ROW LEVEL SECURITY;
CREATE POLICY persona_terreno_policy ON persona_terreno
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = persona_terreno.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE junta_miembros ENABLE ROW LEVEL SECURITY;
CREATE POLICY junta_miembros_policy ON junta_miembros
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = junta_miembros.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE faena_participacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY faena_participacion_policy ON faena_participacion
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = faena_participacion.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE asistencia_asamblea ENABLE ROW LEVEL SECURITY;
CREATE POLICY asistencia_asamblea_policy ON asistencia_asamblea
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = asistencia_asamblea.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE caja_categorias ENABLE ROW LEVEL SECURITY;
CREATE POLICY caja_categorias_policy ON caja_categorias
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = caja_categorias.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY caja_movimientos_policy ON caja_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND EXISTS (
    SELECT 1 FROM tenant_users tu
    WHERE tu.id_tenant = caja_movimientos.id_tenant
      AND tu.id_user = current_setting('app.user_id', true)::bigint
      AND tu.estado = 'ACTIVO'
  )
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE conceptos_cobro ENABLE ROW LEVEL SECURITY;
CREATE POLICY conceptos_cobro_policy ON conceptos_cobro
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE obligaciones_persona ENABLE ROW LEVEL SECURITY;
CREATE POLICY obligaciones_persona_policy ON obligaciones_persona
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE obligacion_pagos ENABLE ROW LEVEL SECURITY;
CREATE POLICY obligacion_pagos_policy ON obligacion_pagos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE obligacion_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY obligacion_movimientos_policy ON obligacion_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE creditos_persona ENABLE ROW LEVEL SECURITY;
CREATE POLICY creditos_persona_policy ON creditos_persona
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE credito_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY credito_movimientos_policy ON credito_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

ALTER TABLE documentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY documentos_policy ON documentos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
)
WITH CHECK (id_tenant = current_setting('app.tenant_id', true)::bigint);

-- Forzar RLS
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_users FORCE ROW LEVEL SECURITY;
ALTER TABLE personas FORCE ROW LEVEL SECURITY;
ALTER TABLE terrenos FORCE ROW LEVEL SECURITY;
ALTER TABLE juntas_directivas FORCE ROW LEVEL SECURITY;
ALTER TABLE faenas FORCE ROW LEVEL SECURITY;
ALTER TABLE asambleas FORCE ROW LEVEL SECURITY;
ALTER TABLE bienes FORCE ROW LEVEL SECURITY;
ALTER TABLE persona_terreno FORCE ROW LEVEL SECURITY;
ALTER TABLE junta_miembros FORCE ROW LEVEL SECURITY;
ALTER TABLE faena_participacion FORCE ROW LEVEL SECURITY;
ALTER TABLE asistencia_asamblea FORCE ROW LEVEL SECURITY;
ALTER TABLE caja_categorias FORCE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos FORCE ROW LEVEL SECURITY;
ALTER TABLE conceptos_cobro FORCE ROW LEVEL SECURITY;
ALTER TABLE obligaciones_persona FORCE ROW LEVEL SECURITY;
ALTER TABLE obligacion_pagos FORCE ROW LEVEL SECURITY;
ALTER TABLE obligacion_movimientos FORCE ROW LEVEL SECURITY;
ALTER TABLE creditos_persona FORCE ROW LEVEL SECURITY;
ALTER TABLE credito_movimientos FORCE ROW LEVEL SECURITY;
ALTER TABLE documentos FORCE ROW LEVEL SECURITY;

-- =========================================================
-- FIN V3
-- =========================================================
