-- =========================================================
--  MULTI-TENANT (PostgreSQL)
--  BASE: villa_union (una sola BD, cientos de asociaciones)
-- =========================================================
-- Nota: En PostgreSQL crea la BD y conéctate antes:
--   CREATE DATABASE villa_union;
--   \c villa_union

-- =========================================================
--  TABLA: tenants (asociaciones)
-- =========================================================
CREATE TABLE tenants (
  id_tenant    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre       VARCHAR(150) NOT NULL,
  ruc          VARCHAR(15),
  dni          VARCHAR(8),
  estado       VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  observaciones VARCHAR(300),

  CONSTRAINT pk_tenants00 PRIMARY KEY (id_tenant),
  CONSTRAINT ux_tenants00 UNIQUE (nombre),
  CONSTRAINT ck_tenants00 CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE INDEX inx_tenants00 ON tenants (estado);

-- =========================================================
--  TABLA: personas
-- =========================================================

CREATE TABLE personas (
  id_tenant            BIGINT NOT NULL,
  id_persona           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  nombres                    VARCHAR(100) NOT NULL,
  apellidoPaterno            VARCHAR(100) NOT NULL,
  apellidoMaterno            VARCHAR(100) NOT NULL,
  dni                  VARCHAR(15),
  telefono             VARCHAR(20),
  referencia_vivienda  VARCHAR(200),

  tipo_participante    VARCHAR(20) NOT NULL DEFAULT 'NO_PADRONADO',
  estado               VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

  fecha_registro       DATE NOT NULL,
  observaciones        TEXT,

  CONSTRAINT pk_personas00 PRIMARY KEY (id_tenant, id_persona),
  CONSTRAINT fk_personas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_personas00 CHECK (tipo_participante IN ('PADRONADO','NO_PADRONADO','INVITADO')),
  CONSTRAINT ck_personas01 CHECK (estado IN ('ACTIVO','SUSPENDIDO','RETIRADO'))
);

CREATE INDEX inx_personas00 ON personas (id_tenant);
CREATE INDEX inx_personas01 ON personas (id_tenant, dni);
CREATE INDEX inx_personas02 ON personas (id_tenant, apellidoPaterno,apellidoMaterno, nombres);


-- =========================================================
--  TABLA: terrenos
-- =========================================================
CREATE TABLE terrenos (
  id_tenant     BIGINT NOT NULL,
  id_terreno    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  descripcion   VARCHAR(200) NOT NULL,
  area_aprox_m2 NUMERIC(10,2),
  estado        VARCHAR(20) NOT NULL DEFAULT 'EN_USO',
  observaciones TEXT,

  CONSTRAINT pk_terrenos00 PRIMARY KEY (id_tenant, id_terreno),
  CONSTRAINT fk_terrenos00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_terrenos00 CHECK (estado IN ('EN_USO','EN_VENTA','VENDIDO_PARCIAL','VENDIDO_TOTAL','RESERVA'))
);

CREATE INDEX inx_terrenos00 ON terrenos (id_tenant);
CREATE INDEX inx_terrenos01 ON terrenos (id_tenant, estado);

-- =========================================================
--  TABLA: juntas_directivas
-- =========================================================
CREATE TABLE juntas_directivas (
  id_tenant     BIGINT NOT NULL,
  id_junta      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  nombre        VARCHAR(100) NOT NULL,
  fecha_inicio  DATE NOT NULL,
  fecha_fin     DATE,
  estado        VARCHAR(10) NOT NULL DEFAULT 'VIGENTE',
  observaciones TEXT,

  CONSTRAINT pk_juntas_directivas00 PRIMARY KEY (id_tenant, id_junta),
  CONSTRAINT fk_juntas_directivas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_juntas_directivas00 CHECK (estado IN ('VIGENTE','CESADA'))
);

CREATE INDEX inx_juntas_directivas00 ON juntas_directivas (id_tenant);
CREATE INDEX inx_juntas_directivas01 ON juntas_directivas (id_tenant, estado);
CREATE INDEX inx_juntas_directivas02 ON juntas_directivas (id_tenant, fecha_inicio, fecha_fin);

-- =========================================================
--  TABLA: faenas
-- =========================================================
CREATE TABLE faenas (
  id_tenant     BIGINT NOT NULL,
  id_faena      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha         DATE NOT NULL,
  descripcion   VARCHAR(200) NOT NULL,
  lugar         VARCHAR(200),
  observaciones TEXT,

  CONSTRAINT pk_faenas00 PRIMARY KEY (id_tenant, id_faena),
  CONSTRAINT fk_faenas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant)
);

CREATE INDEX inx_faenas00 ON faenas (id_tenant);
CREATE INDEX inx_faenas01 ON faenas (id_tenant, fecha);

-- =========================================================
--  TABLA: asambleas
-- =========================================================
CREATE TABLE asambleas (
  id_tenant        BIGINT NOT NULL,
  id_asamblea      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha            TIMESTAMP NOT NULL,
  tipo             VARCHAR(15) NOT NULL,
  tema_principal   VARCHAR(200) NOT NULL,
  lugar            VARCHAR(200),
  quorum_requerido INT,
  observaciones    TEXT,

  CONSTRAINT pk_asambleas00 PRIMARY KEY (id_tenant, id_asamblea),
  CONSTRAINT fk_asambleas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_asambleas00 CHECK (tipo IN ('ORDINARIA','EXTRAORDINARIA'))
);

CREATE INDEX inx_asambleas00 ON asambleas (id_tenant);
CREATE INDEX inx_asambleas01 ON asambleas (id_tenant, fecha);
CREATE INDEX inx_asambleas02 ON asambleas (id_tenant, tipo);

-- =========================================================
--  TABLA: bienes
-- =========================================================
CREATE TABLE bienes (
  id_tenant      BIGINT NOT NULL,
  id_bien        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  descripcion    VARCHAR(200) NOT NULL,
  tipo           VARCHAR(50),
  cantidad       INT NOT NULL,
  valor_estimado NUMERIC(10,2),
  ubicacion      VARCHAR(200),
  fecha_alta     DATE NOT NULL,
  fecha_baja     DATE,
  estado         VARCHAR(20) NOT NULL DEFAULT 'BUENO',
  observaciones  TEXT,

  CONSTRAINT pk_bienes00 PRIMARY KEY (id_tenant, id_bien),
  CONSTRAINT fk_bienes00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_bienes00 CHECK (estado IN ('BUENO','REGULAR','MALO','DADO_DE_BAJA'))
);

CREATE INDEX inx_bienes00 ON bienes (id_tenant);
CREATE INDEX inx_bienes01 ON bienes (id_tenant, estado);
CREATE INDEX inx_bienes02 ON bienes (id_tenant, tipo);

-- =========================================================
--  TABLA: usuarios
-- =========================================================
CREATE TABLE usuarios (
  id_tenant      BIGINT NOT NULL,
  id_usuario     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  username       VARCHAR(50) NOT NULL,
  password_hash  VARCHAR(255) NOT NULL,
  rol            VARCHAR(15) NOT NULL,
  estado         VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',

  id_persona     BIGINT NULL,
  fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
  observaciones  TEXT,

  CONSTRAINT pk_usuarios00 PRIMARY KEY (id_tenant, id_usuario),
  CONSTRAINT fk_usuarios00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  -- username único por tenant
  CONSTRAINT ux_usuarios00 UNIQUE (id_tenant, username),

  CONSTRAINT ck_usuarios00 CHECK (rol IN ('ADMIN','PRESIDENTE','SECRETARIO','TESORERA','VOCAL')),
  CONSTRAINT ck_usuarios01 CHECK (estado IN ('ACTIVO','INACTIVO')),

  -- persona del mismo tenant (FK compuesta)
  CONSTRAINT fk_usuarios01 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona)
);

CREATE INDEX inx_usuarios00 ON usuarios (id_tenant);
CREATE INDEX inx_usuarios01 ON usuarios (id_tenant, rol, estado);
CREATE INDEX inx_usuarios02 ON usuarios (id_tenant, id_persona);

-- =========================================================
--  TABLA: persona_terreno (M:N)
-- =========================================================
CREATE TABLE persona_terreno (
  id_tenant              BIGINT NOT NULL,
  id_persona_terreno     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_persona             BIGINT NOT NULL,
  id_terreno             BIGINT NOT NULL,
  tipo_relacion          VARCHAR(15) NOT NULL,
  porcentaje_participacion NUMERIC(5,2),

  CONSTRAINT pk_persona_terreno00 PRIMARY KEY (id_tenant, id_persona_terreno),
  CONSTRAINT fk_persona_terreno00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_persona_terreno00 CHECK (tipo_relacion IN ('PROPIETARIO','POSEEDOR','COPROPIETARIO','FAMILIAR','OTRO')),

  CONSTRAINT fk_persona_terreno01 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_persona_terreno02 FOREIGN KEY (id_tenant, id_terreno)
    REFERENCES terrenos (id_tenant, id_terreno),

  CONSTRAINT ux_persona_terreno00 UNIQUE (id_tenant, id_persona, id_terreno)
);

CREATE INDEX inx_persona_terreno00 ON persona_terreno (id_tenant);
CREATE INDEX inx_persona_terreno01 ON persona_terreno (id_tenant, id_terreno);
CREATE INDEX inx_persona_terreno02 ON persona_terreno (id_tenant, tipo_relacion);

-- =========================================================
--  TABLA: junta_miembros
-- =========================================================
CREATE TABLE junta_miembros (
  id_tenant       BIGINT NOT NULL,
  id_junta_miembro BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_junta        BIGINT NOT NULL,
  id_persona      BIGINT NOT NULL,
  cargo           VARCHAR(20) NOT NULL,
  fecha_inicio    DATE NOT NULL,
  fecha_fin       DATE,

  CONSTRAINT pk_junta_miembros00 PRIMARY KEY (id_tenant, id_junta_miembro),
  CONSTRAINT fk_junta_miembros00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_junta_miembros00 CHECK (cargo IN ('PRESIDENTE','VICEPRESIDENTE','SECRETARIO','TESORERO','VOCAL','OTRO')),

  CONSTRAINT fk_junta_miembros01 FOREIGN KEY (id_tenant, id_junta)
    REFERENCES juntas_directivas (id_tenant, id_junta),
  CONSTRAINT fk_junta_miembros02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona)
);

CREATE INDEX inx_junta_miembros00 ON junta_miembros (id_tenant);
CREATE INDEX inx_junta_miembros01 ON junta_miembros (id_tenant, id_junta);
CREATE INDEX inx_junta_miembros02 ON junta_miembros (id_tenant, id_persona);
CREATE INDEX inx_junta_miembros03 ON junta_miembros (id_tenant, cargo);

-- =========================================================
--  TABLA: faena_participacion
-- =========================================================
CREATE TABLE faena_participacion (
  id_tenant              BIGINT NOT NULL,
  id_faena_participacion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_faena       BIGINT NOT NULL,
  id_persona     BIGINT NOT NULL,
  asistio        BOOLEAN NOT NULL,
  hora_llegada   TIME,
  multa_generada BOOLEAN NOT NULL DEFAULT FALSE,
  monto_multa    NUMERIC(10,2),

  CONSTRAINT pk_faena_participacion00 PRIMARY KEY (id_tenant, id_faena_participacion),
  CONSTRAINT fk_faena_participacion00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_faena_participacion00 CHECK (
    (multa_generada = FALSE AND monto_multa IS NULL)
    OR
    (multa_generada = TRUE AND monto_multa IS NOT NULL)
  ),

  CONSTRAINT fk_faena_participacion01 FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_faena_participacion02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),

  -- opcional útil: no duplicar a la misma persona en la misma faena
  CONSTRAINT ux_faena_participacion00 UNIQUE (id_tenant, id_faena, id_persona)
);

CREATE INDEX inx_faena_participacion00 ON faena_participacion (id_tenant);
CREATE INDEX inx_faena_participacion01 ON faena_participacion (id_tenant, id_faena);
CREATE INDEX inx_faena_participacion02 ON faena_participacion (id_tenant, id_persona);
CREATE INDEX inx_faena_participacion03 ON faena_participacion (id_tenant, asistio);

-- =========================================================
--  TABLA: asistencia_asamblea
-- =========================================================
CREATE TABLE asistencia_asamblea (
  id_tenant      BIGINT NOT NULL,
  id_asistencia  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_asamblea    BIGINT NOT NULL,
  id_persona     BIGINT NOT NULL,
  asistio        BOOLEAN NOT NULL,
  hora_llegada   TIME,
  es_padronado_en_momento BOOLEAN NOT NULL,
  observaciones  TEXT,

  CONSTRAINT pk_asistencia_asamblea00 PRIMARY KEY (id_tenant, id_asistencia),
  CONSTRAINT fk_asistencia_asamblea00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT fk_asistencia_asamblea01 FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_asistencia_asamblea02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),

  -- opcional útil: no duplicar persona por asamblea
  CONSTRAINT ux_asistencia_asamblea00 UNIQUE (id_tenant, id_asamblea, id_persona)
);

CREATE INDEX inx_asistencia_asamblea00 ON asistencia_asamblea (id_tenant);
CREATE INDEX inx_asistencia_asamblea01 ON asistencia_asamblea (id_tenant, id_asamblea);
CREATE INDEX inx_asistencia_asamblea02 ON asistencia_asamblea (id_tenant, id_persona);
CREATE INDEX inx_asistencia_asamblea03 ON asistencia_asamblea (id_tenant, asistio);

-- =========================================================
--  TABLA: caja_movimientos
-- =========================================================
CREATE TABLE caja_movimientos (
  id_tenant      BIGINT NOT NULL,
  id_movimiento  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha          DATE NOT NULL,
  tipo           VARCHAR(10) NOT NULL,
  monto          NUMERIC(10,2) NOT NULL,

  categoria      VARCHAR(40) NOT NULL,

  id_persona     BIGINT NULL,
  id_faena       BIGINT NULL,
  id_asamblea    BIGINT NULL,
  id_bien        BIGINT NULL,
  id_usuario     BIGINT NULL,

  descripcion    VARCHAR(255),
  medio_pago     VARCHAR(20) NOT NULL,
  doc_referencia VARCHAR(100),
  observaciones  TEXT,

  CONSTRAINT pk_caja_movimientos00 PRIMARY KEY (id_tenant, id_movimiento),
  CONSTRAINT fk_caja_movimientos00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_caja_movimientos00 CHECK (tipo IN ('INGRESO','GASTO')),
  CONSTRAINT ck_caja_movimientos01 CHECK (categoria IN (
    'APORTE','MULTA_FAENA','MULTA_ASAMBLEA','APORTE_VOLUNTARIO','DONACION',
    'SALDO_INICIAL_JUNTA_ANTERIOR','OTRO_INGRESO',
    'GASTO_OPERATIVO','MATERIAL_OBRA','MOVILIDAD','REUNION','SERVICIOS',
    'COMPRA_BIEN','OTRO_GASTO'
  )),
  CONSTRAINT ck_caja_movimientos02 CHECK (medio_pago IN ('EFECTIVO','TRANSFERENCIA','YAPE','PLIN','OTRO')),

  CONSTRAINT fk_caja_movimientos01 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_caja_movimientos02 FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_caja_movimientos03 FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_caja_movimientos04 FOREIGN KEY (id_tenant, id_bien)
    REFERENCES bienes (id_tenant, id_bien),
  CONSTRAINT fk_caja_movimientos05 FOREIGN KEY (id_tenant, id_usuario)
    REFERENCES usuarios (id_tenant, id_usuario)
);

CREATE INDEX inx_caja_movimientos00 ON caja_movimientos (id_tenant);
CREATE INDEX inx_caja_movimientos01 ON caja_movimientos (id_tenant, fecha, tipo);
CREATE INDEX inx_caja_movimientos02 ON caja_movimientos (id_tenant, categoria);
CREATE INDEX inx_caja_movimientos03 ON caja_movimientos (id_tenant, id_persona);
CREATE INDEX inx_caja_movimientos04 ON caja_movimientos (id_tenant, id_usuario);

-- =========================================================
--  RLS (Row Level Security) Multi-tenant
--  Patrón: USING + WITH CHECK
-- =========================================================

-- tenants (opcional: normalmente lo ven solo admins globales)
-- OJO: si activas RLS aquí, necesitarás políticas especiales para "super admin".
-- ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;

-- personas
ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
CREATE POLICY personas_tenant_policy
ON personas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- usuarios
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY usuarios_tenant_policy
ON usuarios
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- caja_movimientos
ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY caja_movimientos_tenant_policy
ON caja_movimientos
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- terrenos
ALTER TABLE terrenos ENABLE ROW LEVEL SECURITY;
CREATE POLICY terrenos_tenant_policy
ON terrenos
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- juntas_directivas
ALTER TABLE juntas_directivas ENABLE ROW LEVEL SECURITY;
CREATE POLICY juntas_directivas_tenant_policy
ON juntas_directivas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- faenas
ALTER TABLE faenas ENABLE ROW LEVEL SECURITY;
CREATE POLICY faenas_tenant_policy
ON faenas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- asambleas
ALTER TABLE asambleas ENABLE ROW LEVEL SECURITY;
CREATE POLICY asambleas_tenant_policy
ON asambleas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- bienes
ALTER TABLE bienes ENABLE ROW LEVEL SECURITY;
CREATE POLICY bienes_tenant_policy
ON bienes
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- persona_terreno
ALTER TABLE persona_terreno ENABLE ROW LEVEL SECURITY;
CREATE POLICY persona_terreno_tenant_policy
ON persona_terreno
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- junta_miembros
ALTER TABLE junta_miembros ENABLE ROW LEVEL SECURITY;
CREATE POLICY junta_miembros_tenant_policy
ON junta_miembros
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- faena_participacion
ALTER TABLE faena_participacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY faena_participacion_tenant_policy
ON faena_participacion
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- asistencia_asamblea
ALTER TABLE asistencia_asamblea ENABLE ROW LEVEL SECURITY;
CREATE POLICY asistencia_asamblea_tenant_policy
ON asistencia_asamblea
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);


-- Asegurar que RLS se aplique incluso al owner
ALTER TABLE personas FORCE ROW LEVEL SECURITY;
ALTER TABLE usuarios FORCE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos FORCE ROW LEVEL SECURITY;
ALTER TABLE terrenos FORCE ROW LEVEL SECURITY;
ALTER TABLE juntas_directivas FORCE ROW LEVEL SECURITY;
ALTER TABLE faenas FORCE ROW LEVEL SECURITY;
ALTER TABLE asambleas FORCE ROW LEVEL SECURITY;
ALTER TABLE bienes FORCE ROW LEVEL SECURITY;
ALTER TABLE persona_terreno FORCE ROW LEVEL SECURITY;
ALTER TABLE junta_miembros FORCE ROW LEVEL SECURITY;
ALTER TABLE faena_participacion FORCE ROW LEVEL SECURITY;
ALTER TABLE asistencia_asamblea FORCE ROW LEVEL SECURITY;
