-- =========================================================
--  MULTI-TENANT (PostgreSQL)
--  BASE: villa_union (una sola BD, cientos de asociaciones)
--  NUEVO FLUJO: usuario global + membresías por tenant
-- =========================================================



-- =========================================================
--  0) USERS GLOBALES (LOGIN)
-- =========================================================
CREATE TABLE auth_users (
  id_user       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email         VARCHAR(120) NOT NULL,
  nombres         VARCHAR(100) NOT NULL,
  apellidos       VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  estado        VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
  email_verified  BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  updated_at      TIMESTAMP NOT NULL DEFAULT now(),
  last_login_at TIMESTAMP NULL,

  CONSTRAINT pk_auth_users PRIMARY KEY (id_user),
  CONSTRAINT ux_auth_users_email UNIQUE (email),
  CONSTRAINT ck_auth_users_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE INDEX inx_auth_users00 ON auth_users (estado);


CREATE TABLE auth_login_logs (
  id_log        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  id_user       BIGINT NULL,  -- null si fue intento fallido con email inexistente
  email         VARCHAR(120) NOT NULL,

  login_at      TIMESTAMP NOT NULL DEFAULT now(),
  success       BOOLEAN NOT NULL,

  ip_address    VARCHAR(45),
  user_agent    TEXT,

  failure_reason VARCHAR(100),

  CONSTRAINT fk_login_user FOREIGN KEY (id_user)
    REFERENCES auth_users(id_user)
);

CREATE INDEX inx_login_logs_user ON auth_login_logs (id_user);
CREATE INDEX inx_login_logs_date ON auth_login_logs (login_at);
CREATE INDEX inx_login_logs_success ON auth_login_logs (success);

-- =========================================================
--  1) TENANTS (asociaciones / juntas)
--  - owner_user_id = dueño/administrador principal (OWNER)
-- =========================================================
CREATE TABLE tenants (
  id_tenant     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre        VARCHAR(150) NOT NULL,
  ruc           VARCHAR(15),
  dni           VARCHAR(8),
  estado        VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  observaciones VARCHAR(300),

  owner_user_id BIGINT NULL,

  CONSTRAINT pk_tenants00 PRIMARY KEY (id_tenant),
  CONSTRAINT ux_tenants00 UNIQUE (nombre),
  CONSTRAINT ck_tenants00 CHECK (estado IN ('ACTIVO','INACTIVO')),
  CONSTRAINT fk_tenants_owner FOREIGN KEY (owner_user_id) REFERENCES auth_users(id_user)
);

CREATE INDEX inx_tenants00 ON tenants (estado);
CREATE INDEX inx_tenants01 ON tenants (owner_user_id);

-- =========================================================
--  2) MEMBRESÍAS: usuarios ↔ tenant (compartir juntas)
--  - role: OWNER / ADMIN / MEMBER
--  - transferir owner = cambiar role
-- =========================================================
CREATE TABLE tenant_users (
  id_tenant   BIGINT NOT NULL,
  id_user     BIGINT NOT NULL,

  role        VARCHAR(15) NOT NULL DEFAULT 'MEMBER',
  estado      VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
  joined_at   TIMESTAMP NOT NULL DEFAULT now(),
  invited_by  BIGINT NULL,

  -- opcional: vincular a una persona del padrón de ESA junta
  id_persona  BIGINT NULL,

  CONSTRAINT pk_tenant_users PRIMARY KEY (id_tenant, id_user),

  CONSTRAINT fk_tu_tenant  FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_tu_user    FOREIGN KEY (id_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_tu_invited FOREIGN KEY (invited_by) REFERENCES auth_users(id_user),

  CONSTRAINT ck_tu_role   CHECK (role IN ('OWNER','ADMIN','MEMBER')),
  CONSTRAINT ck_tu_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE INDEX inx_tenant_users00 ON tenant_users (id_user);
CREATE INDEX inx_tenant_users01 ON tenant_users (id_tenant, role, estado);

-- Solo 1 OWNER activo por tenant
CREATE UNIQUE INDEX ux_one_owner_per_tenant
ON tenant_users (id_tenant)
WHERE role = 'OWNER' AND estado = 'ACTIVO';

-- =========================================================
--  3) INVITACIONES (opcional recomendado para "compartir")
-- =========================================================
CREATE TABLE tenant_invitations (
  id_invitation BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_tenant     BIGINT NOT NULL, -- A qué junta pertenece la invitación.
  email         VARCHAR(120) NOT NULL, --A qué correo se está invitando.(No necesitas que el usuario exista aún.)
  role          VARCHAR(15) NOT NULL DEFAULT 'MEMBER', --Qué rol tendrá si acepta.
  token         VARCHAR(120) NOT NULL, --Token único para aceptar la invitación.
  status        VARCHAR(15) NOT NULL DEFAULT 'PENDING', --Estado actual de la invitación.
  expires_at    TIMESTAMP NOT NULL, --Fecha límite para aceptar.
  invited_by    BIGINT NOT NULL, --Qué usuario hizo la invitación.
  created_at    TIMESTAMP NOT NULL DEFAULT now(), --Cuándo se creó la invitación.

  CONSTRAINT pk_tenant_invitations PRIMARY KEY (id_invitation),
  CONSTRAINT fk_inv_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_inv_user   FOREIGN KEY (invited_by) REFERENCES auth_users(id_user),

  CONSTRAINT ux_inv_token UNIQUE (token),
  CONSTRAINT ck_inv_role CHECK (role IN ('ADMIN','MEMBER')),
  CONSTRAINT ck_inv_status CHECK (status IN ('PENDING','ACCEPTED','REVOKED','EXPIRED'))
);

CREATE INDEX inx_inv00 ON tenant_invitations (id_tenant);
CREATE INDEX inx_inv01 ON tenant_invitations (email);
CREATE INDEX inx_inv02 ON tenant_invitations (status);

-- =========================================================
--  4) TABLAS OPERATIVAS (TENANT-SCOPED) - se mantienen
-- =========================================================

-- =========================================================
--  TABLA: personas
-- =========================================================
CREATE TABLE personas (
  id_tenant            BIGINT NOT NULL,
  id_persona           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  nombres              VARCHAR(100) NOT NULL,
  apellidoPaterno      VARCHAR(100) NOT NULL,
  apellidoMaterno      VARCHAR(100) NOT NULL,
  dni                  VARCHAR(15),
  telefono             VARCHAR(20),
  referencia_vivienda  VARCHAR(200),

  tipo_participante    VARCHAR(20) NOT NULL DEFAULT 'NO_PADRONADO',
  estado               VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

  fecha_registro       DATE NOT NULL,
  observaciones        TEXT,

  CONSTRAINT pk_personas00 PRIMARY KEY (id_tenant, id_persona),
  CONSTRAINT fk_personas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_personas00 CHECK (tipo_participante IN ('PADRONADO','NO_PADRONADO','INVITADO')),
  CONSTRAINT ck_personas01 CHECK (estado IN ('ACTIVO','SUSPENDIDO','RETIRADO'))
);

CREATE INDEX inx_personas00 ON personas (id_tenant);
CREATE INDEX inx_personas01 ON personas (id_tenant, dni);
CREATE INDEX inx_personas02 ON personas (id_tenant, apellidoPaterno,apellidoMaterno, nombres);

-- Vincular tenant_users.id_persona -> personas (misma junta)
/*
ALTER TABLE tenant_users
  ADD CONSTRAINT fk_tu_persona
  FOREIGN KEY (id_tenant, id_persona)
  REFERENCES personas (id_tenant, id_persona);
*/
-- =========================================================
--  TABLA: terrenos
-- =========================================================
CREATE TABLE terrenos (
  id_tenant     BIGINT NOT NULL,
  id_terreno    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  descripcion   VARCHAR(200) NOT NULL,
  area_aprox_m2 NUMERIC(10,2),
  estado        VARCHAR(20) NOT NULL DEFAULT 'EN_USO',
  observaciones TEXT,

  CONSTRAINT pk_terrenos00 PRIMARY KEY (id_tenant, id_terreno),
  CONSTRAINT fk_terrenos00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_terrenos00 CHECK (estado IN ('EN_USO','EN_VENTA','VENDIDO_PARCIAL','VENDIDO_TOTAL','RESERVA'))
);

CREATE INDEX inx_terrenos00 ON terrenos (id_tenant);
CREATE INDEX inx_terrenos01 ON terrenos (id_tenant, estado);

-- =========================================================
--  TABLA: juntas_directivas
-- =========================================================
CREATE TABLE juntas_directivas (
  id_tenant     BIGINT NOT NULL,
  id_junta      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  nombre        VARCHAR(100) NOT NULL,
  fecha_inicio  DATE NOT NULL,
  fecha_fin     DATE,
  estado        VARCHAR(10) NOT NULL DEFAULT 'VIGENTE',
  observaciones TEXT,

  CONSTRAINT pk_juntas_directivas00 PRIMARY KEY (id_tenant, id_junta),
  CONSTRAINT fk_juntas_directivas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_juntas_directivas00 CHECK (estado IN ('VIGENTE','CESADA'))
);

CREATE INDEX inx_juntas_directivas00 ON juntas_directivas (id_tenant);
CREATE INDEX inx_juntas_directivas01 ON juntas_directivas (id_tenant, estado);
CREATE INDEX inx_juntas_directivas02 ON juntas_directivas (id_tenant, fecha_inicio, fecha_fin);

-- =========================================================
--  TABLA: faenas
-- =========================================================
CREATE TABLE faenas (
  id_tenant     BIGINT NOT NULL,
  id_faena      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha         DATE NOT NULL,
  descripcion   VARCHAR(200) NOT NULL,
  lugar         VARCHAR(200),
  observaciones TEXT,

  CONSTRAINT pk_faenas00 PRIMARY KEY (id_tenant, id_faena),
  CONSTRAINT fk_faenas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant)
);

CREATE INDEX inx_faenas00 ON faenas (id_tenant);
CREATE INDEX inx_faenas01 ON faenas (id_tenant, fecha);

-- =========================================================
--  TABLA: asambleas
-- =========================================================
CREATE TABLE asambleas (
  id_tenant        BIGINT NOT NULL,
  id_asamblea      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha            TIMESTAMP NOT NULL,
  tipo             VARCHAR(15) NOT NULL,
  tema_principal   VARCHAR(200) NOT NULL,
  lugar            VARCHAR(200),
  quorum_requerido INT,
  observaciones    TEXT,

  CONSTRAINT pk_asambleas00 PRIMARY KEY (id_tenant, id_asamblea),
  CONSTRAINT fk_asambleas00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_asambleas00 CHECK (tipo IN ('ORDINARIA','EXTRAORDINARIA'))
);

CREATE INDEX inx_asambleas00 ON asambleas (id_tenant);
CREATE INDEX inx_asambleas01 ON asambleas (id_tenant, fecha);
CREATE INDEX inx_asambleas02 ON asambleas (id_tenant, tipo);

-- =========================================================
--  TABLA: bienes
-- =========================================================
CREATE TABLE bienes (
  id_tenant      BIGINT NOT NULL,
  id_bien        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  descripcion    VARCHAR(200) NOT NULL,
  tipo           VARCHAR(50),
  cantidad       INT NOT NULL,
  valor_estimado NUMERIC(10,2),
  ubicacion      VARCHAR(200),
  fecha_alta     DATE NOT NULL,
  fecha_baja     DATE,
  estado         VARCHAR(20) NOT NULL DEFAULT 'BUENO',
  observaciones  TEXT,

  CONSTRAINT pk_bienes00 PRIMARY KEY (id_tenant, id_bien),
  CONSTRAINT fk_bienes00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_bienes00 CHECK (estado IN ('BUENO','REGULAR','MALO','DADO_DE_BAJA'))
);

CREATE INDEX inx_bienes00 ON bienes (id_tenant);
CREATE INDEX inx_bienes01 ON bienes (id_tenant, estado);
CREATE INDEX inx_bienes02 ON bienes (id_tenant, tipo);

-- =========================================================
--  TABLA: persona_terreno (M:N)
-- =========================================================
CREATE TABLE persona_terreno (
  id_tenant                 BIGINT NOT NULL,
  id_persona_terreno        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_persona                BIGINT NOT NULL,
  id_terreno                BIGINT NOT NULL,
  tipo_relacion             VARCHAR(15) NOT NULL,
  porcentaje_participacion  NUMERIC(5,2),

  CONSTRAINT pk_persona_terreno00 PRIMARY KEY (id_tenant, id_persona_terreno),
  CONSTRAINT fk_persona_terreno00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_persona_terreno00 CHECK (tipo_relacion IN ('PROPIETARIO','POSEEDOR','COPROPIETARIO','FAMILIAR','OTRO')),

  CONSTRAINT fk_persona_terreno01 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_persona_terreno02 FOREIGN KEY (id_tenant, id_terreno)
    REFERENCES terrenos (id_tenant, id_terreno),

  CONSTRAINT ux_persona_terreno00 UNIQUE (id_tenant, id_persona, id_terreno)
);

CREATE INDEX inx_persona_terreno00 ON persona_terreno (id_tenant);
CREATE INDEX inx_persona_terreno01 ON persona_terreno (id_tenant, id_terreno);
CREATE INDEX inx_persona_terreno02 ON persona_terreno (id_tenant, tipo_relacion);

-- =========================================================
--  TABLA: junta_miembros
-- =========================================================
CREATE TABLE junta_miembros (
  id_tenant        BIGINT NOT NULL,
  id_junta_miembro BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_junta         BIGINT NOT NULL,
  id_persona       BIGINT NOT NULL,
  cargo            VARCHAR(20) NOT NULL,
  fecha_inicio     DATE NOT NULL,
  fecha_fin        DATE,

  CONSTRAINT pk_junta_miembros00 PRIMARY KEY (id_tenant, id_junta_miembro),
  CONSTRAINT fk_junta_miembros00 FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),

  CONSTRAINT ck_junta_miembros00 CHECK (cargo IN ('PRESIDENTE','VICEPRESIDENTE','SECRETARIO','TESORERO','VOCAL','OTRO')),

  CONSTRAINT fk_junta_miembros01 FOREIGN KEY (id_tenant, id_junta)
    REFERENCES juntas_directivas (id_tenant, id_junta),
  CONSTRAINT fk_junta_miembros02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona)
);

CREATE INDEX inx_junta_miembros00 ON junta_miembros (id_tenant);
CREATE INDEX inx_junta_miembros01 ON junta_miembros (id_tenant, id_junta);
CREATE INDEX inx_junta_miembros02 ON junta_miembros (id_tenant, id_persona);
CREATE INDEX inx_junta_miembros03 ON junta_miembros (id_tenant, cargo);

-- =========================================================
--  TABLA: faena_participacion
-- =========================================================
-- =========================================================
--  TABLA: faena_participacion (mejorada)
-- =========================================================
CREATE TABLE faena_participacion (
  id_tenant              BIGINT NOT NULL,
  id_faena_participacion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_faena       BIGINT NOT NULL,
  id_persona     BIGINT NOT NULL,

  estado         VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada   TIME,

  cant_personas_extra SMALLINT NOT NULL DEFAULT 0,

  multa_generada BOOLEAN NOT NULL DEFAULT FALSE,
  monto_multa    NUMERIC(10,2),

  observaciones  TEXT,

  -- Auditoría
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  created_by_user  BIGINT NOT NULL,
  updated_at       TIMESTAMP NULL,
  updated_by_user  BIGINT NULL,

  -- Anulación lógica
  anulado          BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at       TIMESTAMP NULL,
  anulado_by_user  BIGINT NULL,
  motivo_anulacion TEXT NULL,

  CONSTRAINT pk_faena_participacion00 PRIMARY KEY (id_tenant, id_faena_participacion),
  CONSTRAINT fk_faena_participacion00 FOREIGN KEY (id_tenant)
    REFERENCES tenants(id_tenant),

  CONSTRAINT fk_faena_participacion01 FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_faena_participacion02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),

  CONSTRAINT ux_faena_participacion00 UNIQUE (id_tenant, id_faena, id_persona),

  -- Estados válidos
  CONSTRAINT ck_faena_participacion_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),

  -- Multa consistente
  CONSTRAINT ck_faena_participacion_multa CHECK (
    (multa_generada = FALSE AND monto_multa IS NULL)
    OR
    (multa_generada = TRUE AND monto_multa IS NOT NULL AND monto_multa >= 0)
  ),

  -- Acompañantes: no negativos y con tope razonable
  CONSTRAINT ck_faena_participacion_extra CHECK (
    cant_personas_extra >= 0 AND cant_personas_extra <= 20
  ),

  -- Consistencia de anulación
  CONSTRAINT ck_faena_participacion_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE  AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),

  -- Auditoría: quién crea/modifica/anula (usuarios globales)
  CONSTRAINT fk_faena_participacion_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users (id_user),
  CONSTRAINT fk_faena_participacion_updated_by FOREIGN KEY (updated_by_user)
    REFERENCES auth_users (id_user),
  CONSTRAINT fk_faena_participacion_anulado_by FOREIGN KEY (anulado_by_user)
    REFERENCES auth_users (id_user)
);

CREATE INDEX inx_faena_participacion00 ON faena_participacion (id_tenant);
CREATE INDEX inx_faena_participacion01 ON faena_participacion (id_tenant, id_faena);
CREATE INDEX inx_faena_participacion02 ON faena_participacion (id_tenant, id_persona);
CREATE INDEX inx_faena_participacion03 ON faena_participacion (id_tenant, estado);
CREATE INDEX inx_faena_participacion04 ON faena_participacion (id_tenant, anulado);
CREATE INDEX inx_faena_participacion05 ON faena_participacion (id_tenant, created_at);

-- =========================================================
--  TABLA: asistencia_asamblea (mejorada)
-- =========================================================
CREATE TABLE asistencia_asamblea (
  id_tenant      BIGINT NOT NULL,
  id_asistencia  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_asamblea    BIGINT NOT NULL,
  id_persona     BIGINT NOT NULL,

  estado         VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada   TIME,

  es_padronado_en_momento BOOLEAN NOT NULL,
  observaciones  TEXT,

  -- Auditoría
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  created_by_user  BIGINT NOT NULL,
  updated_at       TIMESTAMP NULL,
  updated_by_user  BIGINT NULL,

  -- Anulación lógica
  anulado          BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at       TIMESTAMP NULL,
  anulado_by_user  BIGINT NULL,
  motivo_anulacion TEXT NULL,

  CONSTRAINT pk_asistencia_asamblea00 PRIMARY KEY (id_tenant, id_asistencia),
  CONSTRAINT fk_asistencia_asamblea00 FOREIGN KEY (id_tenant)
    REFERENCES tenants(id_tenant),

  CONSTRAINT fk_asistencia_asamblea01 FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_asistencia_asamblea02 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),

  CONSTRAINT ux_asistencia_asamblea00 UNIQUE (id_tenant, id_asamblea, id_persona),

  -- Estados válidos
  CONSTRAINT ck_asistencia_asamblea_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),

  -- Consistencia de anulación
  CONSTRAINT ck_asistencia_asamblea_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE  AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),

  -- Auditoría: usuarios globales
  CONSTRAINT fk_asistencia_asamblea_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users (id_user),
  CONSTRAINT fk_asistencia_asamblea_updated_by FOREIGN KEY (updated_by_user)
    REFERENCES auth_users (id_user),
  CONSTRAINT fk_asistencia_asamblea_anulado_by FOREIGN KEY (anulado_by_user)
    REFERENCES auth_users (id_user)
);

CREATE INDEX inx_asistencia_asamblea00 ON asistencia_asamblea (id_tenant);
CREATE INDEX inx_asistencia_asamblea01 ON asistencia_asamblea (id_tenant, id_asamblea);
CREATE INDEX inx_asistencia_asamblea02 ON asistencia_asamblea (id_tenant, id_persona);
CREATE INDEX inx_asistencia_asamblea03 ON asistencia_asamblea (id_tenant, estado);
CREATE INDEX inx_asistencia_asamblea04 ON asistencia_asamblea (id_tenant, anulado);
CREATE INDEX inx_asistencia_asamblea05 ON asistencia_asamblea (id_tenant, created_at);

-- =========================================================
--  TABLA: caja_movimientos (FINAL: auditoría + anulación)
-- =========================================================
CREATE TABLE caja_movimientos (
  id_tenant      BIGINT NOT NULL,
  id_movimiento  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  fecha          DATE NOT NULL,
  tipo           VARCHAR(10) NOT NULL,
  monto          NUMERIC(10,2) NOT NULL,

  categoria      VARCHAR(40) NOT NULL,

  id_persona     BIGINT NULL,
  id_faena       BIGINT NULL,
  id_asamblea    BIGINT NULL,
  id_bien        BIGINT NULL,

  -- Usuario responsable del registro (actor)
  id_user        BIGINT NOT NULL,

  descripcion    VARCHAR(255),
  medio_pago     VARCHAR(20) NOT NULL,
  doc_referencia VARCHAR(100),
  observaciones  TEXT,

  -- Auditoría
  created_at       TIMESTAMP NOT NULL DEFAULT now(),
  created_by_user  BIGINT NOT NULL,
  updated_at       TIMESTAMP NULL,
  updated_by_user  BIGINT NULL,

  -- Anulación lógica
  anulado          BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at       TIMESTAMP NULL,
  anulado_by_user  BIGINT NULL,
  motivo_anulacion TEXT NULL,

  CONSTRAINT pk_caja_movimientos00 PRIMARY KEY (id_tenant, id_movimiento),
  CONSTRAINT fk_caja_movimientos00 FOREIGN KEY (id_tenant)
    REFERENCES tenants(id_tenant),

  CONSTRAINT ck_caja_movimientos00 CHECK (tipo IN ('INGRESO','GASTO')),
  CONSTRAINT ck_caja_movimientos01 CHECK (categoria IN (
    'APORTE','MULTA_FAENA','MULTA_ASAMBLEA','APORTE_VOLUNTARIO','DONACION',
    'SALDO_INICIAL_JUNTA_ANTERIOR','OTRO_INGRESO',
    'GASTO_OPERATIVO','MATERIAL_OBRA','MOVILIDAD','REUNION','SERVICIOS',
    'COMPRA_BIEN','OTRO_GASTO'
  )),
  CONSTRAINT ck_caja_movimientos02 CHECK (medio_pago IN ('EFECTIVO','TRANSFERENCIA','YAPE','PLIN','OTRO')),

  -- Consistencia de anulación
  CONSTRAINT ck_caja_movimientos_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE  AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),

  -- Relaciones de negocio
  CONSTRAINT fk_caja_movimientos01 FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_caja_movimientos02 FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_caja_movimientos03 FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_caja_movimientos04 FOREIGN KEY (id_tenant, id_bien)
    REFERENCES bienes (id_tenant, id_bien),

  -- Usuario actor + auditoría (todos a auth_users)
  CONSTRAINT fk_caja_movimientos_user FOREIGN KEY (id_user)
    REFERENCES auth_users (id_user),

  CONSTRAINT fk_caja_movimientos_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users (id_user),

  CONSTRAINT fk_caja_movimientos_updated_by FOREIGN KEY (updated_by_user)
    REFERENCES auth_users (id_user),

  CONSTRAINT fk_caja_movimientos_anulado_by FOREIGN KEY (anulado_by_user)
    REFERENCES auth_users (id_user)
);

-- Índices principales
CREATE INDEX inx_caja_movimientos00 ON caja_movimientos (id_tenant);
CREATE INDEX inx_caja_movimientos01 ON caja_movimientos (id_tenant, fecha, tipo);
CREATE INDEX inx_caja_movimientos02 ON caja_movimientos (id_tenant, categoria);
CREATE INDEX inx_caja_movimientos03 ON caja_movimientos (id_tenant, id_persona);
CREATE INDEX inx_caja_movimientos04 ON caja_movimientos (id_tenant, id_user);

-- Índices útiles para auditoría / filtros frecuentes
CREATE INDEX inx_caja_movimientos05 ON caja_movimientos (id_tenant, created_at);
CREATE INDEX inx_caja_movimientos06 ON caja_movimientos (id_tenant, anulado);
-- =========================================================
--  5) RLS (Row Level Security)
--  Estrategia práctica:
--   - Para tablas operativas: sigue usando app.tenant_id (igual que antes)
--   - Para tenants/tenant_users: usa app.user_id para listar "mis juntas"
-- =========================================================

-- 5.1) Tenants: habilitar RLS para que un usuario vea solo sus tenants
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;

-- A) Ver tenants donde soy miembro activo
CREATE POLICY tenants_select_by_membership
ON tenants
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM tenant_users tu
    WHERE tu.id_tenant = tenants.id_tenant
      AND tu.id_user = current_setting('app.user_id')::bigint
      AND tu.estado = 'ACTIVO'
  )
);

-- B) Ver tenants donde soy owner (útil para recién creado)
CREATE POLICY tenants_select_by_owner
ON tenants
FOR SELECT
USING (
  owner_user_id = current_setting('app.user_id')::bigint
);

-- C) Permitir INSERT solo si el owner es el usuario actual
CREATE POLICY tenants_insert_by_owner
ON tenants
FOR INSERT
WITH CHECK (
  owner_user_id = current_setting('app.user_id')::bigint
);

-- (Opcional) Permitir UPDATE solo al owner
CREATE POLICY tenants_update_by_owner
ON tenants
FOR UPDATE
USING (
  owner_user_id = current_setting('app.user_id')::bigint
)
WITH CHECK (
  owner_user_id = current_setting('app.user_id')::bigint
);

-- 5.2) Tenant_users: un usuario puede ver solo sus memberships
ALTER TABLE tenant_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_users_self_policy
ON tenant_users
USING (
  id_user = current_setting('app.user_id')::bigint
)
WITH CHECK (
  id_user = current_setting('app.user_id')::bigint
);

-- (Opcional) permitir que ADMIN/OWNER gestione miembros (se suele hacer en backend)
-- Si lo quieres a nivel BD con RLS avanzado, te lo armo también.

-- 5.3) Tablas tenant-scoped (igual que tu patrón original)
ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
CREATE POLICY personas_tenant_policy
ON personas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;
CREATE POLICY caja_movimientos_tenant_policy
ON caja_movimientos
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE terrenos ENABLE ROW LEVEL SECURITY;
CREATE POLICY terrenos_tenant_policy
ON terrenos
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE juntas_directivas ENABLE ROW LEVEL SECURITY;
CREATE POLICY juntas_directivas_tenant_policy
ON juntas_directivas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE faenas ENABLE ROW LEVEL SECURITY;
CREATE POLICY faenas_tenant_policy
ON faenas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE asambleas ENABLE ROW LEVEL SECURITY;
CREATE POLICY asambleas_tenant_policy
ON asambleas
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE bienes ENABLE ROW LEVEL SECURITY;
CREATE POLICY bienes_tenant_policy
ON bienes
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE persona_terreno ENABLE ROW LEVEL SECURITY;
CREATE POLICY persona_terreno_tenant_policy
ON persona_terreno
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE junta_miembros ENABLE ROW LEVEL SECURITY;
CREATE POLICY junta_miembros_tenant_policy
ON junta_miembros
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE faena_participacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY faena_participacion_tenant_policy
ON faena_participacion
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

ALTER TABLE asistencia_asamblea ENABLE ROW LEVEL SECURITY;
CREATE POLICY asistencia_asamblea_tenant_policy
ON asistencia_asamblea
USING (id_tenant = current_setting('app.tenant_id')::bigint)
WITH CHECK (id_tenant = current_setting('app.tenant_id')::bigint);

-- Forzar RLS incluso para el owner (como tu script original)
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_users FORCE ROW LEVEL SECURITY;

ALTER TABLE personas FORCE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos FORCE ROW LEVEL SECURITY;
ALTER TABLE terrenos FORCE ROW LEVEL SECURITY;
ALTER TABLE juntas_directivas FORCE ROW LEVEL SECURITY;
ALTER TABLE faenas FORCE ROW LEVEL SECURITY;
ALTER TABLE asambleas FORCE ROW LEVEL SECURITY;
ALTER TABLE bienes FORCE ROW LEVEL SECURITY;
ALTER TABLE persona_terreno FORCE ROW LEVEL SECURITY;
ALTER TABLE junta_miembros FORCE ROW LEVEL SECURITY;
ALTER TABLE faena_participacion FORCE ROW LEVEL SECURITY;
ALTER TABLE asistencia_asamblea FORCE ROW LEVEL SECURITY;

-- =========================================================
-- FIN
-- =========================================================