/*
===============================================================================
 JUNTAS CLOUD V4 - MODELO MULTI-TENANT CON RLS
 PostgreSQL
===============================================================================

Objetivo:
  - Cualquier usuario registrado puede crear una o varias juntas (tenants).
  - Distintos tenants pueden tener el mismo nombre, tipo y número de documento.
  - La identidad y el aislamiento de cada junta se basan exclusivamente en id_tenant.
  - El creador queda registrado como OWNER del tenant.
  - El OWNER o un ADMIN puede invitar personas por correo electrónico.
  - La membresía se crea únicamente cuando la invitación es aceptada.
  - Cada tenant tiene como máximo un OWNER activo.
  - El OWNER puede transferir la propiedad a otro miembro activo.
  - Las operaciones sensibles se ejecutan mediante funciones SECURITY DEFINER.

IMPORTANTE:
  1. Este script debe ejecutarse con un usuario administrador de la base de datos.
  2. El backend debe establecer el usuario autenticado al iniciar cada transacción:

       SELECT set_config('app.user_id', '123', true);

     El tercer parámetro TRUE limita el valor a la transacción actual.
  3. No se debe permitir que el cliente establezca libremente app.user_id.
     Esta responsabilidad corresponde exclusivamente al backend.
  4. Al final del script se incluyen GRANT de ejemplo. Reemplazar
     app_authenticated por el rol real utilizado por la aplicación.
===============================================================================
DROP DATABASE IF EXISTS juntascloudv4;
CREATE DATABASE juntascloudv4;
*/

-- =============================================================================
-- 0. EXTENSIONES
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- =============================================================================
-- 1. ROL INTERNO PARA FUNCIONES RLS
-- =============================================================================
--
-- Las funciones auxiliares consultan tenant_users, tabla que también tiene RLS.
-- Para evitar recursión infinita se utiliza un rol NOLOGIN con BYPASSRLS.
-- Este rol nunca debe utilizarse para conectar la aplicación.
--
-- CREATE ROLE requiere privilegios administrativos en PostgreSQL.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'juntas_rls_definer'
  ) THEN
    CREATE ROLE juntas_rls_definer NOLOGIN BYPASSRLS;
  END IF;
END;
$$;


-- =============================================================================
-- 2. FUNCIONES GENERALES
-- =============================================================================

-- Actualiza automáticamente la columna updated_at.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;


-- Recupera el usuario autenticado establecido por el backend.
CREATE OR REPLACE FUNCTION public.app_current_user_id()
RETURNS BIGINT
LANGUAGE sql
STABLE
SET search_path = pg_catalog, public
AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::BIGINT;
$$;


-- =============================================================================
-- 3. MÓDULOS GLOBALES
-- =============================================================================

CREATE TABLE public.app_modules (
  module_code          VARCHAR(80)  NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  grupo                VARCHAR(100) NOT NULL,
  orden                INTEGER      NOT NULL DEFAULT 0,
  estado               BOOLEAN      NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_app_modules PRIMARY KEY (module_code)
);


-- =============================================================================
-- 4. USUARIOS GLOBALES Y AUTENTICACIÓN
-- =============================================================================

CREATE TABLE public.auth_users (
  id_user              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email                CITEXT       NOT NULL,
  nombres              VARCHAR(100) NOT NULL,
  apellidos            VARCHAR(100) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  estado               VARCHAR(15)  NOT NULL DEFAULT 'ACTIVO',
  email_verified       BOOLEAN      NOT NULL DEFAULT FALSE,
  email_verified_at    TIMESTAMPTZ  NULL,
  last_login_at        TIMESTAMPTZ  NULL,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pk_auth_users PRIMARY KEY (id_user),
  CONSTRAINT ux_auth_users_email UNIQUE (email),
  CONSTRAINT ck_auth_users_estado
    CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO')),
  CONSTRAINT ck_auth_users_email_verified
    CHECK (
      (email_verified = FALSE AND email_verified_at IS NULL)
      OR
      (email_verified = TRUE AND email_verified_at IS NOT NULL)
    )
);

CREATE INDEX ix_auth_users_estado
  ON public.auth_users (estado);

CREATE TRIGGER trg_auth_users_updated_at
BEFORE UPDATE ON public.auth_users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.auth_user_tokens (
  id_token             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_user              BIGINT       NOT NULL,
  token_hash           VARCHAR(255) NOT NULL,
  token_type           VARCHAR(30)  NOT NULL,
  expires_at           TIMESTAMPTZ  NOT NULL,
  used_at              TIMESTAMPTZ  NULL,
  revoked_at           TIMESTAMPTZ  NULL,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  created_ip           VARCHAR(45)  NULL,
  user_agent           TEXT         NULL,

  CONSTRAINT pk_auth_user_tokens PRIMARY KEY (id_token),
  CONSTRAINT fk_auth_user_tokens_user
    FOREIGN KEY (id_user)
    REFERENCES public.auth_users (id_user),
  CONSTRAINT ux_auth_user_tokens_hash UNIQUE (token_hash),
  CONSTRAINT ck_auth_user_tokens_type
    CHECK (token_type IN ('VERIFY_EMAIL', 'RESET_PASSWORD', 'CHANGE_EMAIL')),
  CONSTRAINT ck_auth_user_tokens_dates
    CHECK (expires_at > created_at),
  CONSTRAINT ck_auth_user_tokens_completion
    CHECK (used_at IS NULL OR revoked_at IS NULL)
);

CREATE INDEX ix_auth_user_tokens_user
  ON public.auth_user_tokens (id_user);

CREATE INDEX ix_auth_user_tokens_user_type
  ON public.auth_user_tokens (id_user, token_type);

CREATE INDEX ix_auth_user_tokens_expires
  ON public.auth_user_tokens (expires_at);


CREATE TABLE public.auth_login_logs (
  id_log               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_user              BIGINT      NULL,
  email                CITEXT      NOT NULL,
  login_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  success              BOOLEAN     NOT NULL,
  ip_address           VARCHAR(45) NULL,
  user_agent           TEXT        NULL,
  failure_reason       VARCHAR(100) NULL,

  CONSTRAINT pk_auth_login_logs PRIMARY KEY (id_log),
  CONSTRAINT fk_auth_login_logs_user
    FOREIGN KEY (id_user)
    REFERENCES public.auth_users (id_user)
);

CREATE INDEX ix_auth_login_logs_user
  ON public.auth_login_logs (id_user);

CREATE INDEX ix_auth_login_logs_date
  ON public.auth_login_logs (login_at);

CREATE INDEX ix_auth_login_logs_success
  ON public.auth_login_logs (success);


-- =============================================================================
-- 5. TENANTS / JUNTAS DIRECTIVAS
-- =============================================================================
--
-- El propietario no se almacena en esta tabla. La fuente de verdad del OWNER
-- es tenant_users, porque un usuario puede tener diferentes roles en distintos
-- tenants.
--
-- nombre, tipo_documento y numero_documento son datos descriptivos y pueden
-- repetirse entre tenants. id_tenant es el identificador único del workspace.

CREATE TABLE public.tenants (
  id_tenant            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre               VARCHAR(150) NOT NULL,
  tipo_documento       VARCHAR(15)  NULL,
  numero_documento     VARCHAR(20)  NULL,
  
  -- Indica el propósito del espacio de trabajo.
  tenant_type          VARCHAR(15) NOT NULL DEFAULT 'PRACTICE',

  estado               VARCHAR(15)  NOT NULL DEFAULT 'ACTIVO',
  observaciones        VARCHAR(300) NULL,
  deleted_at           TIMESTAMPTZ NULL,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenants PRIMARY KEY (id_tenant),
  CONSTRAINT ck_tenants_nombre
    CHECK (btrim(nombre) <> ''),
  CONSTRAINT ck_tenants_estado
    CHECK (estado IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO')),
  CONSTRAINT ck_tenants_tipo_documento
    CHECK (
      tipo_documento IS NULL
      OR tipo_documento IN ('RUC', 'DNI', 'OTRO')
    ),
  CONSTRAINT ck_tenants_documento
    CHECK (
      (tipo_documento IS NULL AND numero_documento IS NULL)
      OR
      (tipo_documento IS NOT NULL AND numero_documento IS NOT NULL)
    ),
  CONSTRAINT ck_tenants_type
    CHECK (
      tenant_type IN ('OFFICIAL', 'PRACTICE', 'DEMO')
    )
);

CREATE INDEX ix_tenants_estado
  ON public.tenants (estado);

-- Índice no único para agilizar búsquedas por documento.
-- Se permiten varios tenants con el mismo nombre, tipo_documento y
-- numero_documento, porque cada espacio de trabajo se identifica por id_tenant.
CREATE INDEX ix_tenants_documento
  ON public.tenants (tipo_documento, numero_documento)
  WHERE tipo_documento IS NOT NULL
    AND numero_documento IS NOT NULL;

CREATE TRIGGER trg_tenants_updated_at
BEFORE UPDATE ON public.tenants
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =============================================================================
-- 6. PERFILES FUNCIONALES DEL TENANT
-- =============================================================================
--
-- role en tenant_users controla privilegios administrativos:
--   OWNER, ADMIN, MEMBER.
--
-- tenant_profiles controla permisos funcionales del negocio:
--   PRESIDENTE, TESORERO, SECRETARIO, VOCAL, etc.

CREATE TABLE public.tenant_profiles (
  id_profile           BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  id_tenant            BIGINT       NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  descripcion          TEXT         NULL,
  estado               BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenant_profiles PRIMARY KEY (id_profile),
  CONSTRAINT fk_tenant_profiles_tenant
    FOREIGN KEY (id_tenant)
    REFERENCES public.tenants (id_tenant),
  CONSTRAINT ux_tenant_profiles_nombre
    UNIQUE (id_tenant, nombre),
  -- Necesaria para las FK compuestas que validan pertenencia al mismo tenant.
  CONSTRAINT ux_tenant_profiles_tenant_profile
    UNIQUE (id_tenant, id_profile),
  CONSTRAINT ck_tenant_profiles_nombre
    CHECK (btrim(nombre) <> '')
);

CREATE INDEX ix_tenant_profiles_tenant_estado
  ON public.tenant_profiles (id_tenant, estado);

CREATE TRIGGER trg_tenant_profiles_updated_at
BEFORE UPDATE ON public.tenant_profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.tenant_profile_modules (
  id_profile           BIGINT      NOT NULL,
  module_code          VARCHAR(80) NOT NULL,
  access_level         VARCHAR(20) NOT NULL DEFAULT 'SIN_ACCESO',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenant_profile_modules
    PRIMARY KEY (id_profile, module_code),
  CONSTRAINT fk_tenant_profile_modules_profile
    FOREIGN KEY (id_profile)
    REFERENCES public.tenant_profiles (id_profile)
    ON DELETE CASCADE,
  CONSTRAINT fk_tenant_profile_modules_module
    FOREIGN KEY (module_code)
    REFERENCES public.app_modules (module_code),
  CONSTRAINT ck_tenant_profile_modules_access
    CHECK (
      access_level IN ('SIN_ACCESO', 'SOLO_LECTURA', 'ACCESO_TOTAL')
    )
);

CREATE TRIGGER trg_tenant_profile_modules_updated_at
BEFORE UPDATE ON public.tenant_profile_modules
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =============================================================================
-- 7. MEMBRESÍAS DEL TENANT
-- =============================================================================
--
-- Aquí solo existen usuarios que ya pertenecen al tenant.
-- Las invitaciones pendientes se almacenan exclusivamente en
-- tenant_invitations para evitar duplicidad y desincronización de estados.

CREATE TABLE public.tenant_users (
  id_tenant            BIGINT      NOT NULL,
  id_user              BIGINT      NOT NULL,
  role                 VARCHAR(15) NOT NULL DEFAULT 'MEMBER',
  estado               VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  joined_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at             TIMESTAMPTZ NULL,
  invited_by           BIGINT      NULL,
  id_persona           BIGINT      NULL,
  id_profile           BIGINT      NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenant_users
    PRIMARY KEY (id_tenant, id_user),
  CONSTRAINT fk_tenant_users_tenant
    FOREIGN KEY (id_tenant)
    REFERENCES public.tenants (id_tenant),
  CONSTRAINT fk_tenant_users_user
    FOREIGN KEY (id_user)
    REFERENCES public.auth_users (id_user),
  CONSTRAINT fk_tenant_users_invited_by
    FOREIGN KEY (invited_by)
    REFERENCES public.auth_users (id_user),
  -- Impide asignar un perfil perteneciente a otro tenant.
  CONSTRAINT fk_tenant_users_profile
    FOREIGN KEY (id_tenant, id_profile)
    REFERENCES public.tenant_profiles (id_tenant, id_profile),
  CONSTRAINT ck_tenant_users_role
    CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
  CONSTRAINT ck_tenant_users_estado
    CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT ck_tenant_users_dates
    CHECK (
      (estado = 'ACTIVO' AND ended_at IS NULL)
      OR
      (estado = 'INACTIVO' AND ended_at IS NOT NULL AND ended_at >= joined_at)
    )
);

CREATE INDEX ix_tenant_users_user_estado
  ON public.tenant_users (id_user, estado);

CREATE INDEX ix_tenant_users_tenant_role_estado
  ON public.tenant_users (id_tenant, role, estado);

-- Garantiza como máximo un OWNER activo por tenant.
CREATE UNIQUE INDEX ux_tenant_users_one_active_owner
  ON public.tenant_users (id_tenant)
  WHERE role = 'OWNER'
    AND estado = 'ACTIVO';

CREATE TRIGGER trg_tenant_users_updated_at
BEFORE UPDATE ON public.tenant_users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =============================================================================
-- 8. INVITACIONES
-- =============================================================================
--
-- Una invitación puede enviarse aunque el destinatario todavía no tenga cuenta.
-- tenant_users se crea o reactiva únicamente al aceptar la invitación.

CREATE TABLE public.tenant_invitations (
  id_invitation        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT       NOT NULL,
  email                CITEXT       NOT NULL,
  role                 VARCHAR(15)  NOT NULL DEFAULT 'MEMBER',
  id_profile           BIGINT       NULL,
  token_hash           VARCHAR(255) NOT NULL,
  status               VARCHAR(15)  NOT NULL DEFAULT 'PENDING',
  expires_at           TIMESTAMPTZ  NOT NULL,
  accepted_at          TIMESTAMPTZ  NULL,
  rejected_at          TIMESTAMPTZ  NULL,
  revoked_at           TIMESTAMPTZ  NULL,
  invited_by           BIGINT       NOT NULL,
  message              VARCHAR(500) NULL,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pk_tenant_invitations PRIMARY KEY (id_invitation),
  CONSTRAINT fk_tenant_invitations_tenant
    FOREIGN KEY (id_tenant)
    REFERENCES public.tenants (id_tenant),
  CONSTRAINT fk_tenant_invitations_invited_by
    FOREIGN KEY (invited_by)
    REFERENCES public.auth_users (id_user),
  CONSTRAINT fk_tenant_invitations_profile
    FOREIGN KEY (id_tenant, id_profile)
    REFERENCES public.tenant_profiles (id_tenant, id_profile),
  CONSTRAINT ux_tenant_invitations_token_hash UNIQUE (token_hash),
  CONSTRAINT ck_tenant_invitations_role
    CHECK (role IN ('ADMIN', 'MEMBER')),
  CONSTRAINT ck_tenant_invitations_status
    CHECK (
      status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', 'EXPIRED')
    ),
  CONSTRAINT ck_tenant_invitations_expiration
    CHECK (expires_at > created_at),
  CONSTRAINT ck_tenant_invitations_status_dates
    CHECK (
      (status = 'PENDING'
        AND accepted_at IS NULL
        AND rejected_at IS NULL
        AND revoked_at IS NULL)
      OR
      (status = 'ACCEPTED'
        AND accepted_at IS NOT NULL
        AND rejected_at IS NULL
        AND revoked_at IS NULL)
      OR
      (status = 'REJECTED'
        AND accepted_at IS NULL
        AND rejected_at IS NOT NULL
        AND revoked_at IS NULL)
      OR
      (status = 'REVOKED'
        AND accepted_at IS NULL
        AND rejected_at IS NULL
        AND revoked_at IS NOT NULL)
      OR
      (status = 'EXPIRED'
        AND accepted_at IS NULL
        AND rejected_at IS NULL
        AND revoked_at IS NULL)
    )
);

CREATE INDEX ix_tenant_invitations_tenant_status
  ON public.tenant_invitations (id_tenant, status);

CREATE INDEX ix_tenant_invitations_email_status
  ON public.tenant_invitations (email, status);

CREATE INDEX ix_tenant_invitations_expires
  ON public.tenant_invitations (expires_at)
  WHERE status = 'PENDING';

-- Solo puede existir una invitación pendiente por correo dentro del mismo tenant.
CREATE UNIQUE INDEX ux_tenant_invitations_pending_email
  ON public.tenant_invitations (id_tenant, email)
  WHERE status = 'PENDING';

CREATE TRIGGER trg_tenant_invitations_updated_at
BEFORE UPDATE ON public.tenant_invitations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();







-- =========================================================
-- 4) PERSONAS
-- =========================================================
CREATE TABLE public.personas (
  id_persona           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  nro_padron           INTEGER NULL,

  nombres              VARCHAR(100) NOT NULL,
  apellido_paterno     VARCHAR(100) NOT NULL,
  apellido_materno     VARCHAR(100) NOT NULL,
  dni                  VARCHAR(15),
  email                CITEXT NULL,
  telefono             VARCHAR(20),
  direccion            VARCHAR(200),
  referencia_vivienda  VARCHAR(200),

  tipo_participante    VARCHAR(20) NOT NULL DEFAULT 'NO_PADRONADO',
  estado               VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',

  fecha_registro       DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_baja           DATE NULL,
  observaciones        TEXT,

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_personas PRIMARY KEY (id_persona),

  CONSTRAINT uq_personas_tenant_persona UNIQUE (id_tenant, id_persona),

  CONSTRAINT fk_personas_tenant
    FOREIGN KEY (id_tenant)
    REFERENCES public.tenants (id_tenant),

  CONSTRAINT ck_personas_tipo CHECK (tipo_participante IN ('PADRONADO','NO_PADRONADO','INVITADO')),
  CONSTRAINT ck_personas_estado CHECK (estado IN ('ACTIVO','SUSPENDIDO','RETIRADO','FALLECIDO')),
  CONSTRAINT ck_personas_baja CHECK (fecha_baja IS NULL OR fecha_baja >= fecha_registro),
  CONSTRAINT ck_personas_nro_padron CHECK (nro_padron IS NULL OR nro_padron > 0),
  CONSTRAINT ck_personas_nro_padron_tipo
  CHECK (
    (tipo_participante = 'PADRONADO' AND nro_padron IS NOT NULL)
    OR
    (tipo_participante IN ('NO_PADRONADO', 'INVITADO') AND nro_padron IS NULL)
  )
);

CREATE INDEX inx_personas_tenant ON public.personas (id_tenant);
CREATE INDEX inx_personas_nombre ON public.personas (id_tenant, apellido_paterno, apellido_materno, nombres);

CREATE UNIQUE INDEX ux_personas_nro_padron 
    ON public.personas (id_tenant, nro_padron) 
    WHERE nro_padron IS NOT NULL;

CREATE UNIQUE INDEX ux_personas_dni
    ON public.personas (id_tenant, dni)
    WHERE dni IS NOT NULL;

CREATE UNIQUE INDEX ux_tenant_users_persona
  ON public.tenant_users (id_tenant, id_persona)
  WHERE id_persona IS NOT NULL;

ALTER TABLE public.tenant_users
  ADD CONSTRAINT fk_tenant_users_persona
  FOREIGN KEY (id_tenant, id_persona)
  REFERENCES public.personas (id_tenant, id_persona);

CREATE TRIGGER trg_personas_updated_at
BEFORE UPDATE ON public.personas
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();



/*historial de cambios de condicion en persona para llevar un historial de los cambios*/
CREATE TABLE public.persona_condiciones (
  id_persona_condicion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  id_tenant            BIGINT NOT NULL,
  id_persona           BIGINT NOT NULL,
  condicion            VARCHAR(20) NOT NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE NULL,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_persona_condiciones PRIMARY KEY (id_persona_condicion),
  CONSTRAINT fk_pc_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_pc_user FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_pc_condicion CHECK (
    condicion IN ('PADRONADO','NO_PADRONADO','INVITADO','SUSPENDIDO','RETIRADO','FALLECIDO')
  ),
  CONSTRAINT ck_pc_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);



-- =========================================================
-- 5) TERRENOS / BIENES
-- =========================================================
CREATE TABLE public.terrenos (
  id_terreno           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  codigo_lote          VARCHAR(30),
  manzana              VARCHAR(20),
  numero_lote          VARCHAR(20),
  descripcion          VARCHAR(200) NOT NULL,
  area_aprox_m2        NUMERIC(10,2),
  area_legal_m2        NUMERIC(10,2),
  partida_registral    VARCHAR(50),
  ubicacion            VARCHAR(200),
  estado               VARCHAR(20) NOT NULL DEFAULT 'EN_USO',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_terrenos PRIMARY KEY (id_terreno),
  CONSTRAINT fk_terrenos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_terrenos_tenant_terreno UNIQUE (id_tenant, id_terreno),
  CONSTRAINT ck_terrenos_estado CHECK (
    estado IN ('EN_USO','EN_VENTA','VENDIDO_PARCIAL','VENDIDO_TOTAL','RESERVA')
  )
);
CREATE INDEX inx_terrenos_estado ON public.terrenos (id_tenant, estado);

CREATE TRIGGER trg_terrenos_updated_at
BEFORE UPDATE ON public.terrenos
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();



-- =========================================================
--  TABLA: bienes
-- =========================================================
CREATE TABLE public.bienes (
  id_bien              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  descripcion          VARCHAR(200) NOT NULL,
  tipo                 VARCHAR(50),
  cantidad             INT NOT NULL,
  valor_estimado       NUMERIC(10,2),
  ubicacion            VARCHAR(200),
  fecha_alta           DATE NOT NULL,
  fecha_baja           DATE,
  estado               VARCHAR(20) NOT NULL DEFAULT 'BUENO',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_bienes PRIMARY KEY (id_bien),
  CONSTRAINT fk_bienes_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_bienes_tenant_bien UNIQUE (id_tenant, id_bien),
  CONSTRAINT ck_bienes_estado CHECK (estado IN ('BUENO','REGULAR','MALO','DADO_DE_BAJA'))
);
CREATE INDEX inx_bienes_estado ON public.bienes (id_tenant, estado);
CREATE INDEX inx_bienes_tipo ON public.bienes (id_tenant, tipo);

CREATE TRIGGER trg_bienes_updated_at
BEFORE UPDATE ON public.bienes
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


-- =========================================================
--  TABLA: persona_terreno (M:N)
-- =========================================================
CREATE TABLE public.persona_terreno (
  id_persona_terreno        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant                 BIGINT NOT NULL,
 
  id_persona                BIGINT NOT NULL,
  id_terreno                BIGINT NOT NULL,
  tipo_relacion             VARCHAR(15) NOT NULL,
  porcentaje_participacion  NUMERIC(5,2),

  CONSTRAINT pk_persona_terreno PRIMARY KEY (id_persona_terreno),
  CONSTRAINT fk_pt_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_pt_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_pt_terreno FOREIGN KEY (id_tenant, id_terreno)
    REFERENCES terrenos (id_tenant, id_terreno),
  CONSTRAINT ux_persona_terreno UNIQUE (id_tenant, id_persona, id_terreno),
  CONSTRAINT ck_persona_terreno_tipo CHECK (
    tipo_relacion IN ('PROPIETARIO','POSEEDOR','COPROPIETARIO','FAMILIAR','OTRO')
  )
);



-- =========================================================
-- 6) GOBIERNO DE LA JUNTA
-- =========================================================
-- =========================================================
--  TABLA: juntas_directivas
-- =========================================================
CREATE TABLE public.juntas_directivas (
  id_junta             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  nombre               VARCHAR(100) NOT NULL,
  fecha_eleccion       DATE NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'VIGENTE',
  documento_sustento   VARCHAR(100),
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_juntas_directivas PRIMARY KEY (id_junta),
  CONSTRAINT fk_jd_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_juntas_directivas_tenant_junta UNIQUE (id_tenant, id_junta),
  CONSTRAINT ck_jd_estado CHECK (estado IN ('VIGENTE','CESADA','ANULADA','PROYECTADA')),
  CONSTRAINT ck_jd_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX inx_juntas_directivas_estado ON public.juntas_directivas (id_tenant, estado);

CREATE UNIQUE INDEX ux_junta_vigente
  ON public.juntas_directivas (id_tenant)
  WHERE estado = 'VIGENTE';

CREATE TRIGGER trg_juntas_directivas_updated_at
  BEFORE UPDATE ON public.juntas_directivas
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();



-- =========================================================
--  TABLA: junta_miembros
-- =========================================================
CREATE TABLE public.junta_miembros (
  id_junta_miembro     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  id_junta             BIGINT NOT NULL,
  id_persona           BIGINT NOT NULL,
  cargo                VARCHAR(20) NOT NULL,
  fecha_inicio         DATE NOT NULL,
  fecha_fin            DATE,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_junta_miembros PRIMARY KEY (id_junta_miembro),

  CONSTRAINT fk_jm_junta FOREIGN KEY (id_tenant, id_junta)
    REFERENCES juntas_directivas (id_tenant, id_junta),

  CONSTRAINT fk_jm_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),

  CONSTRAINT ck_jm_cargo CHECK (
    cargo IN ('PRESIDENTE','VICEPRESIDENTE','SECRETARIO','TESORERO','VOCAL','OTRO')
  ),
  CONSTRAINT ck_jm_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX inx_junta_miembros_junta ON public.junta_miembros (id_tenant, id_junta);
CREATE INDEX inx_junta_miembros_persona ON public.junta_miembros (id_tenant, id_persona);

CREATE UNIQUE INDEX ux_junta_presidente_activo
  ON public.junta_miembros (id_tenant, id_junta, cargo)
  WHERE cargo = 'PRESIDENTE' AND fecha_fin IS NULL;

CREATE TRIGGER trg_junta_miembros_updated_at
  BEFORE UPDATE ON public.junta_miembros
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();



CREATE TABLE public.asambleas (
  id_asamblea          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  fecha_programada     TIMESTAMPTZ NOT NULL,
  hora_inicio_real     TIMESTAMPTZ NULL,
  hora_fin_real        TIMESTAMPTZ NULL,
  tipo                 VARCHAR(15) NOT NULL,
  convocatoria         VARCHAR(15) NULL,
  estado               VARCHAR(15) NOT NULL DEFAULT 'PROGRAMADA',
  tema_principal       VARCHAR(200) NOT NULL,
  lugar                VARCHAR(200),
  quorum_requerido     INT,
  quorum_alcanzado     INT NULL,
  numero_acta          VARCHAR(50),
  observaciones        TEXT,
  cerrada_at           TIMESTAMPTZ NULL,
  cerrada_by_user      BIGINT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_asambleas PRIMARY KEY (id_asamblea),
  CONSTRAINT fk_asambleas_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_asambleas_cerrada_by FOREIGN KEY (cerrada_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT uq_asambleas_tenant_asamblea UNIQUE (id_tenant, id_asamblea),
  CONSTRAINT ck_asambleas_tipo CHECK (tipo IN ('ORDINARIA','EXTRAORDINARIA')),
  CONSTRAINT ck_asambleas_convocatoria CHECK (
    convocatoria IS NULL OR convocatoria IN ('PRIMERA','SEGUNDA')
  ),
  CONSTRAINT ck_asambleas_estado CHECK (
    estado IN ('PROGRAMADA','REALIZADA','CANCELADA','CERRADA')
  )
);
CREATE INDEX inx_asambleas_fecha ON public.asambleas (id_tenant, fecha_programada);

CREATE TRIGGER trg_asambleas_updated_at
  BEFORE UPDATE ON public.asambleas
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();



-- =========================================================
--  TABLA: asistencia_asamblea (mejorada)
-- =========================================================
CREATE TABLE public.asistencia_asamblea (
  id_asistencia             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant                 BIGINT NOT NULL,

  id_asamblea               BIGINT NOT NULL,
  id_persona                BIGINT NOT NULL,
  estado                    VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada              TIME,
  es_padronado_en_momento   BOOLEAN NOT NULL,
  tiene_derecho_voto        BOOLEAN NOT NULL DEFAULT FALSE,
  voto_emitido              BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones             TEXT,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user           BIGINT NOT NULL,
  updated_at                TIMESTAMPTZ NULL,
  updated_by_user           BIGINT NULL,

  anulado                   BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at                TIMESTAMPTZ NULL,
  anulado_by_user           BIGINT NULL,
  motivo_anulacion          TEXT NULL,

  CONSTRAINT pk_asistencia_asamblea PRIMARY KEY (id_asistencia),
  CONSTRAINT fk_aa_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_aa_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_aa_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT ux_asistencia_asamblea UNIQUE (id_tenant, id_asamblea, id_persona),
  CONSTRAINT ck_asistencia_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),
  CONSTRAINT ck_asistencia_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),
  CONSTRAINT fk_aa_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_aa_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_aa_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES auth_users(id_user)
);
CREATE INDEX inx_asistencia_asamblea_asamblea ON public.asistencia_asamblea (id_tenant, id_asamblea);
CREATE INDEX inx_asistencia_asamblea_persona ON public.asistencia_asamblea (id_tenant, id_persona);
CREATE INDEX inx_asistencia_asamblea_estado ON public.asistencia_asamblea (id_tenant, estado);


-- =========================================================
-- 7) FAENAS
-- =========================================================
CREATE TABLE public.faenas (
  id_faena             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,
  
  fecha_programada     DATE NOT NULL,
  hora_inicio          TIME NULL,
  hora_fin             TIME NULL,
  descripcion          VARCHAR(200) NOT NULL,
  lugar                VARCHAR(200),
  tipo_faena           VARCHAR(20) NOT NULL DEFAULT 'ORDINARIA',
  es_obligatoria       BOOLEAN NOT NULL DEFAULT TRUE,
  estado               VARCHAR(15) NOT NULL DEFAULT 'PROGRAMADA',
  monto_multa_base     NUMERIC(10,2) NULL,
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_faenas PRIMARY KEY (id_faena),
  CONSTRAINT fk_faenas_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_faenas_tenant_faena UNIQUE (id_tenant, id_faena),
  CONSTRAINT ck_faena_tipo CHECK (tipo_faena IN ('ORDINARIA','EXTRAORDINARIA','RECUPERACION')),
  CONSTRAINT ck_faena_estado CHECK (estado IN ('PROGRAMADA','EJECUTADA','CANCELADA'))
);
CREATE INDEX inx_faenas_fecha ON public.faenas (id_tenant, fecha_programada);

CREATE TRIGGER trg_faenas_updated_at
  BEFORE UPDATE ON public.faenas
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();



-- =========================================================
--  TABLA: faena_participacion
-- =========================================================
CREATE TABLE public.faena_participacion (
  id_faena_participacion    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant                 BIGINT NOT NULL,

  id_faena                  BIGINT NOT NULL,
  id_persona                BIGINT NOT NULL,
  estado                    VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE',
  hora_llegada              TIME,
  cant_personas_extra       SMALLINT NOT NULL DEFAULT 0,
  multa_generada            BOOLEAN NOT NULL DEFAULT FALSE,
  monto_multa               NUMERIC(10,2),
  observaciones             TEXT,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user           BIGINT NOT NULL,
  updated_at                TIMESTAMPTZ NULL,
  updated_by_user           BIGINT NULL,

  anulado                   BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at                TIMESTAMPTZ NULL,
  anulado_by_user           BIGINT NULL,
  motivo_anulacion          TEXT NULL,

  CONSTRAINT pk_faena_participacion PRIMARY KEY (id_faena_participacion),
  CONSTRAINT fk_fp_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_fp_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_fp_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT ux_faena_participacion UNIQUE (id_tenant, id_faena, id_persona),

  CONSTRAINT ck_fp_estado CHECK (
    estado IN ('PENDIENTE','ASISTIO','TARDE','FALTO','JUSTIFICADO')
  ),
  CONSTRAINT ck_fp_multa CHECK (
    (multa_generada = FALSE AND monto_multa IS NULL)
    OR
    (multa_generada = TRUE AND monto_multa IS NOT NULL AND monto_multa >= 0)
  ),
  CONSTRAINT ck_fp_extra CHECK (
    cant_personas_extra >= 0 AND cant_personas_extra <= 20
  ),
  CONSTRAINT ck_fp_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  ),
  CONSTRAINT fk_fp_created_by FOREIGN KEY (created_by_user) REFERENCES public.auth_users(id_user),
  CONSTRAINT fk_fp_updated_by FOREIGN KEY (updated_by_user) REFERENCES public.auth_users(id_user),
  CONSTRAINT fk_fp_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES public.auth_users(id_user)
);

CREATE INDEX inx_fp_faena ON public.faena_participacion (id_tenant, id_faena);
CREATE INDEX inx_fp_persona ON public.faena_participacion (id_tenant, id_persona);
CREATE INDEX inx_fp_estado ON public.faena_participacion (id_tenant, estado);





-- =========================================================
-- 8) CAJA
-- =========================================================
-- =========================================================
--  TABLA: caja_movimientos (FINAL: auditoría + anulación)
-- =========================================================
CREATE TABLE public.caja_categorias (
  id_categoria_caja    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  cod_categoria        VARCHAR(20) NOT NULL,  
  nombre               VARCHAR(150) NOT NULL,
  tipo                 VARCHAR(10) NOT NULL,
  activo               BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_caja_categorias PRIMARY KEY (id_categoria_caja),
  CONSTRAINT fk_ccat_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT ck_ccat_tipo CHECK (tipo IN ('INGRESO','GASTO')),
  CONSTRAINT uq_caja_categorias_tenant_categoria UNIQUE (id_tenant, id_categoria_caja),
  CONSTRAINT ux_ccat_categoria UNIQUE (id_tenant, cod_categoria)
);



CREATE TABLE public.caja_movimientos (
  id_movimiento        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  fecha                DATE NOT NULL,
  tipo                 VARCHAR(10) NOT NULL,
  monto                NUMERIC(10,2) NOT NULL,
  id_categoria_caja    BIGINT NOT NULL,

  id_persona           BIGINT NULL,
  id_faena             BIGINT NULL,
  id_asamblea          BIGINT NULL,
  id_bien              BIGINT NULL,

  id_user              BIGINT NOT NULL,
  descripcion          VARCHAR(255),
  medio_pago           VARCHAR(20) NOT NULL,
  doc_referencia       VARCHAR(100),
  observaciones        TEXT,

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,
  updated_at           TIMESTAMPTZ NULL,
  updated_by_user      BIGINT NULL,

  anulado              BOOLEAN NOT NULL DEFAULT FALSE,
  anulado_at           TIMESTAMPTZ NULL,
  anulado_by_user      BIGINT NULL,
  motivo_anulacion     TEXT NULL,

  CONSTRAINT pk_caja_movimientos PRIMARY KEY (id_movimiento),
  CONSTRAINT fk_cm_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_caja_movimientos_tenant_movimiento UNIQUE (id_tenant, id_movimiento),
  CONSTRAINT fk_cm_categoria FOREIGN KEY (id_tenant, id_categoria_caja)
    REFERENCES caja_categorias (id_tenant, id_categoria_caja),
  CONSTRAINT fk_cm_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_cm_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_cm_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_cm_bien FOREIGN KEY (id_tenant, id_bien)
    REFERENCES bienes (id_tenant, id_bien),
  CONSTRAINT fk_cm_user FOREIGN KEY (id_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_cm_anulado_by FOREIGN KEY (anulado_by_user) REFERENCES auth_users(id_user),

  CONSTRAINT ck_cm_tipo CHECK (tipo IN ('INGRESO','GASTO')),
  CONSTRAINT ck_cm_monto CHECK (monto > 0),
  CONSTRAINT ck_cm_medio_pago CHECK (
    medio_pago IN ('EFECTIVO','TRANSFERENCIA','YAPE','PLIN','OTRO')
  ),
  CONSTRAINT ck_cm_anulado CHECK (
    (anulado = FALSE AND anulado_at IS NULL AND anulado_by_user IS NULL)
    OR
    (anulado = TRUE AND anulado_at IS NOT NULL AND anulado_by_user IS NOT NULL)
  )
);

CREATE INDEX inx_cm_fecha_tipo ON public.caja_movimientos (id_tenant, fecha, tipo);
CREATE INDEX inx_cm_persona ON public.caja_movimientos (id_tenant, id_persona);
CREATE INDEX inx_cm_user ON public.caja_movimientos (id_tenant, id_user);



-- =========================================================
-- 9) OBLIGACIONES / COBRANZA
-- =========================================================
CREATE TABLE public.conceptos_cobro (
  id_concepto_cobro    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  cod_concepto_cobro   VARCHAR(20) NOT NULL,
  nombre               VARCHAR(100) NOT NULL,
  tipo                 VARCHAR(25) NOT NULL,
  activo               BOOLEAN NOT NULL DEFAULT TRUE,
  requiere_periodo     BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones        TEXT,

  CONSTRAINT pk_conceptos_cobro PRIMARY KEY (id_concepto_cobro),
  CONSTRAINT fk_conceptos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_conceptos_cobro_tenant_concepto UNIQUE (id_tenant, id_concepto_cobro),
  CONSTRAINT ck_conceptos_tipo CHECK (
    tipo IN ('CUOTA_ORDINARIA','CUOTA_EXTRAORDINARIA','MULTA_FAENA','MULTA_ASAMBLEA','APORTE','OTRO')
  ),
  CONSTRAINT ux_conceptos_cobro UNIQUE (id_tenant, cod_concepto_cobro)
);



CREATE TABLE public.obligaciones_persona (
  id_obligacion        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  id_persona           BIGINT NOT NULL,
  id_concepto_cobro    BIGINT NOT NULL,
  periodo              VARCHAR(20) NULL,
  fecha_emision        DATE NOT NULL,
  fecha_vencimiento    DATE NULL,

  monto_original       NUMERIC(10,2) NOT NULL,
  monto_pagado         NUMERIC(10,2) NOT NULL DEFAULT 0,
  monto_exonerado      NUMERIC(10,2) NOT NULL DEFAULT 0,
  monto_compensado     NUMERIC(10,2) NOT NULL DEFAULT 0,
  saldo                NUMERIC(10,2) NOT NULL,

  id_faena             BIGINT NULL,
  id_asamblea          BIGINT NULL,

  observaciones        TEXT,
  estado               VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,
  updated_at           TIMESTAMPTZ NULL,
  updated_by_user      BIGINT NULL,

  anulada_at           TIMESTAMPTZ NULL,
  anulada_by_user      BIGINT NULL,
  motivo_anulacion     TEXT NULL,

  CONSTRAINT pk_obligaciones_persona PRIMARY KEY (id_obligacion),
  CONSTRAINT fk_op_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_obligaciones_persona_tenant_obligacion UNIQUE (id_tenant, id_obligacion),
  CONSTRAINT fk_op_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_op_concepto FOREIGN KEY (id_tenant, id_concepto_cobro)
    REFERENCES conceptos_cobro (id_tenant, id_concepto_cobro),
  CONSTRAINT fk_op_faena FOREIGN KEY (id_tenant, id_faena)
    REFERENCES faenas (id_tenant, id_faena),
  CONSTRAINT fk_op_asamblea FOREIGN KEY (id_tenant, id_asamblea)
    REFERENCES asambleas (id_tenant, id_asamblea),
  CONSTRAINT fk_op_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_op_updated_by FOREIGN KEY (updated_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT fk_op_anulada_by FOREIGN KEY (anulada_by_user) REFERENCES auth_users(id_user),

  CONSTRAINT ck_op_montos CHECK (
    monto_original >= 0 AND monto_pagado >= 0 AND monto_exonerado >= 0
    AND monto_compensado >= 0 AND saldo >= 0
  ),
  CONSTRAINT ck_op_estado CHECK (
    estado IN ('PENDIENTE','PARCIAL','PAGADA','EXONERADA','COMPENSADA','ANULADA')
  )
);

CREATE INDEX inx_obligaciones_persona_persona ON public.obligaciones_persona (id_tenant, id_persona);
CREATE INDEX inx_obligaciones_persona_estado ON public.obligaciones_persona (id_tenant, estado);



CREATE TABLE public.obligacion_pagos (
  id_obligacion_pago   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  id_obligacion        BIGINT NOT NULL,
  id_movimiento        BIGINT NOT NULL,
  monto_aplicado       NUMERIC(10,2) NOT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_obligacion_pagos PRIMARY KEY (id_obligacion_pago),
  CONSTRAINT fk_obp_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_obp_obligacion FOREIGN KEY (id_tenant, id_obligacion)
    REFERENCES obligaciones_persona (id_tenant, id_obligacion),
  CONSTRAINT fk_obp_movimiento FOREIGN KEY (id_tenant, id_movimiento)
    REFERENCES caja_movimientos (id_tenant, id_movimiento),
  CONSTRAINT fk_obp_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_obp_monto CHECK (monto_aplicado > 0)
);


CREATE TABLE public.obligacion_movimientos (
  id_obligacion_movimiento  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant                 BIGINT NOT NULL,

  id_obligacion             BIGINT NOT NULL,
  tipo_movimiento           VARCHAR(20) NOT NULL,
  monto                     NUMERIC(10,2) NOT NULL,
  fecha_movimiento          TIMESTAMPTZ NOT NULL DEFAULT now(),
  referencia_tipo           VARCHAR(30) NULL,
  referencia_id             BIGINT NULL,
  observaciones             TEXT,
  created_by_user           BIGINT NOT NULL,

  CONSTRAINT pk_obligacion_movimientos PRIMARY KEY (id_obligacion_movimiento),
  CONSTRAINT fk_om_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_om_obligacion FOREIGN KEY (id_tenant, id_obligacion)
    REFERENCES obligaciones_persona (id_tenant, id_obligacion),
  CONSTRAINT fk_om_created_by FOREIGN KEY (created_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_om_tipo CHECK (
    tipo_movimiento IN (
      'CREACION','PAGO','EXONERACION','AJUSTE_POSITIVO',
      'AJUSTE_NEGATIVO','ANULACION','COMPENSACION'
    )
  ),
  CONSTRAINT ck_om_monto CHECK (monto >= 0)
);



-- =========================================================
-- 10) CRÉDITOS POR FAENAS ADELANTADAS
-- =========================================================
CREATE TABLE public.creditos_persona (
  id_credito           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  id_persona           BIGINT NOT NULL,
  tipo_credito         VARCHAR(20) NOT NULL,
  cantidad_original    NUMERIC(10,2) NOT NULL,
  cantidad_disponible  NUMERIC(10,2) NOT NULL,
  equivalencia_monto   NUMERIC(10,2) NULL,
  referencia_tipo      VARCHAR(30) NULL,
  referencia_id        BIGINT NULL,
  fecha_generacion     TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_vencimiento    TIMESTAMPTZ NULL,
  estado               VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
  observaciones        TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by_user      BIGINT NOT NULL,

  CONSTRAINT pk_creditos_persona PRIMARY KEY (id_credito),
  CONSTRAINT fk_cp_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT uq_creditos_persona_tenant_credito UNIQUE (id_tenant, id_credito),
  CONSTRAINT fk_cp_persona FOREIGN KEY (id_tenant, id_persona)
    REFERENCES personas (id_tenant, id_persona),
  CONSTRAINT fk_cp_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_cp_tipo CHECK (tipo_credito IN ('FAENA_ADELANTADA','BONIFICACION','OTRO')),
  CONSTRAINT ck_cp_estado CHECK (estado IN ('DISPONIBLE','CONSUMIDO','VENCIDO','ANULADO')),
  CONSTRAINT ck_cp_cantidades CHECK (
    cantidad_original > 0 AND cantidad_disponible >= 0
    AND cantidad_disponible <= cantidad_original
  )
);


CREATE TABLE public.credito_movimientos (
  id_credito_movimiento   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant               BIGINT NOT NULL,

  id_credito              BIGINT NOT NULL,
  tipo_movimiento         VARCHAR(20) NOT NULL,
  cantidad                NUMERIC(10,2) NOT NULL,
  fecha_movimiento        TIMESTAMPTZ NOT NULL DEFAULT now(),
  referencia_tipo         VARCHAR(30) NULL,
  referencia_id           BIGINT NULL,
  observaciones           TEXT,
  created_by_user         BIGINT NOT NULL,

  CONSTRAINT pk_credito_movimientos PRIMARY KEY (id_credito_movimiento),
  CONSTRAINT fk_crm_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_crm_credito FOREIGN KEY (id_tenant, id_credito)
    REFERENCES creditos_persona (id_tenant, id_credito),
  CONSTRAINT fk_crm_created_by FOREIGN KEY (created_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_crm_tipo CHECK (
    tipo_movimiento IN ('GENERACION','CONSUMO','AJUSTE','VENCIMIENTO','ANULACION')
  ),
  CONSTRAINT ck_crm_cantidad CHECK (cantidad > 0)
);





-- =========================================================
-- 11) DOCUMENTOS / AUDITORIA
-- =========================================================
CREATE TABLE public.documentos (
  id_documento         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NOT NULL,

  modulo               VARCHAR(30) NOT NULL,
  entidad_id           BIGINT NOT NULL,
  nombre_archivo       VARCHAR(255) NOT NULL,
  nombre_original      VARCHAR(255) NOT NULL,
  mime_type            VARCHAR(100) NOT NULL,
  tamano_bytes         BIGINT NOT NULL,
  storage_path         VARCHAR(500) NOT NULL,
  uploaded_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  uploaded_by_user     BIGINT NOT NULL,
  observaciones        TEXT,

  CONSTRAINT pk_documentos PRIMARY KEY (id_documento),
  CONSTRAINT fk_documentos_tenant FOREIGN KEY (id_tenant) REFERENCES tenants(id_tenant),
  CONSTRAINT fk_documentos_user FOREIGN KEY (uploaded_by_user) REFERENCES auth_users(id_user),
  CONSTRAINT ck_documentos_modulo CHECK (
    modulo IN ('PERSONA','TERRENO','ASAMBLEA','FAENA','BIEN','CAJA','JUNTA_DIRECTIVA')
  )
);

CREATE TABLE public.audit_log (
  id_audit             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant            BIGINT NULL,
  table_name           VARCHAR(100) NOT NULL,
  record_pk            VARCHAR(200) NOT NULL,
  action               VARCHAR(10) NOT NULL,
  old_data             JSONB NULL,
  new_data             JSONB NULL,
  changed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  changed_by_user      BIGINT NULL,
  ip_address           VARCHAR(45),

  CONSTRAINT pk_audit PRIMARY KEY (id_audit),
  CONSTRAINT fk_audit_user FOREIGN KEY (changed_by_user)
    REFERENCES auth_users(id_user),
  CONSTRAINT ck_audit_action CHECK (
    action IN ('INSERT','UPDATE','DELETE','ANULACION')
  )
);




-- =========================================================
-- CATÁLOGOS BASE / PLANTILLAS GLOBALES
-- =========================================================
CREATE TABLE public.caja_categorias_base (
  cod_categoria          VARCHAR(20) NOT NULL,  
  nombre                 VARCHAR(100) NOT NULL,
  tipo                   VARCHAR(10) NOT NULL,
  activo                 BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT pk_caja_categorias_base PRIMARY KEY (cod_categoria),  
  CONSTRAINT ck_caja_categorias_base_tipo CHECK (
    tipo IN ('INGRESO','GASTO')
  )
);

CREATE TABLE public.conceptos_cobro_base (
  cod_concepto_cobro     VARCHAR(20) NOT NULL,

  nombre                 VARCHAR(100) NOT NULL,
  tipo                   VARCHAR(25) NOT NULL,
  activo                 BOOLEAN NOT NULL DEFAULT TRUE,
  requiere_periodo       BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones          TEXT,

  CONSTRAINT pk_conceptos_cobro_base PRIMARY KEY (cod_concepto_cobro),  
  CONSTRAINT ck_conceptos_cobro_base_tipo CHECK (
    tipo IN ('CUOTA_ORDINARIA','CUOTA_EXTRAORDINARIA','MULTA_FAENA','MULTA_ASAMBLEA','APORTE','OTRO')
  )
);





-- =============================================================================
-- 9. PRIVILEGIOS DEL ROL INTERNO
-- =============================================================================

GRANT USAGE, CREATE ON SCHEMA public TO juntas_rls_definer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public
  TO juntas_rls_definer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
  TO juntas_rls_definer;


-- =============================================================================
-- 10. FUNCIONES AUXILIARES PARA RLS
-- =============================================================================

-- Verifica si el usuario autenticado es miembro activo del tenant.
CREATE OR REPLACE FUNCTION public.is_active_tenant_member(
  p_tenant_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.tenant_users tu
    WHERE tu.id_tenant = p_tenant_id
      AND tu.id_user = public.app_current_user_id()
      AND tu.estado = 'ACTIVO'
  );
$$;

ALTER FUNCTION public.is_active_tenant_member(BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.is_active_tenant_member(BIGINT) FROM PUBLIC;


-- Verifica si el usuario autenticado tiene uno de los roles administrativos.
CREATE OR REPLACE FUNCTION public.has_tenant_role(
  p_tenant_id BIGINT,
  p_roles TEXT[]
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.tenant_users tu
    WHERE tu.id_tenant = p_tenant_id
      AND tu.id_user = public.app_current_user_id()
      AND tu.estado = 'ACTIVO'
      AND tu.role = ANY (p_roles)
  );
$$;

ALTER FUNCTION public.has_tenant_role(BIGINT, TEXT[])
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.has_tenant_role(BIGINT, TEXT[]) FROM PUBLIC;


-- Verifica si un correo corresponde al usuario autenticado y está verificado.
-- Evita que las políticas RLS necesiten acceso directo a auth_users.
CREATE OR REPLACE FUNCTION public.is_current_user_verified_email(
  p_email CITEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.auth_users au
    WHERE au.id_user = public.app_current_user_id()
      AND au.estado = 'ACTIVO'
      AND au.email_verified = TRUE
      AND au.email = p_email
  );
$$;

ALTER FUNCTION public.is_current_user_verified_email(CITEXT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.is_current_user_verified_email(CITEXT) FROM PUBLIC;


-- =============================================================================
-- 11. ROW LEVEL SECURITY
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 11.1. TENANTS
-- -----------------------------------------------------------------------------

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants FORCE ROW LEVEL SECURITY;

CREATE POLICY tenants_select_member
ON public.tenants
FOR SELECT
USING (
  public.is_active_tenant_member(id_tenant)
);

CREATE POLICY tenants_update_owner_admin
ON public.tenants
FOR UPDATE
USING (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
)
WITH CHECK (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
);

-- No existe política DELETE. Se recomienda desactivar el tenant en lugar de
-- eliminarlo físicamente.


-- -----------------------------------------------------------------------------
-- 11.2. TENANT_USERS
-- -----------------------------------------------------------------------------

ALTER TABLE public.tenant_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_users FORCE ROW LEVEL SECURITY;

-- Un usuario puede ver sus propias membresías.
-- Además, un miembro activo puede consultar la lista de miembros de su tenant.
CREATE POLICY tenant_users_select
ON public.tenant_users
FOR SELECT
USING (
  id_user = public.app_current_user_id()
  OR public.is_active_tenant_member(id_tenant)
);

-- No se crean políticas INSERT, UPDATE ni DELETE.
-- Las modificaciones se realizan mediante funciones controladas para impedir:
--   - que un ADMIN cree otro OWNER;
--   - que un usuario se ascienda a sí mismo;
--   - que un ADMIN modifique al OWNER;
--   - que el OWNER abandone el tenant sin transferirlo.


-- -----------------------------------------------------------------------------
-- 11.3. TENANT_PROFILES
-- -----------------------------------------------------------------------------

ALTER TABLE public.tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_profiles FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_profiles_select
ON public.tenant_profiles
FOR SELECT
USING (
  public.is_active_tenant_member(id_tenant)
);

CREATE POLICY tenant_profiles_insert
ON public.tenant_profiles
FOR INSERT
WITH CHECK (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
);

CREATE POLICY tenant_profiles_update
ON public.tenant_profiles
FOR UPDATE
USING (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
)
WITH CHECK (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
);

CREATE POLICY tenant_profiles_delete
ON public.tenant_profiles
FOR DELETE
USING (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
);


-- -----------------------------------------------------------------------------
-- 11.4. TENANT_PROFILE_MODULES
-- -----------------------------------------------------------------------------
--
-- tenant_profile_modules no contiene id_tenant. Por ello las políticas obtienen
-- el tenant a través de tenant_profiles.

ALTER TABLE public.tenant_profile_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_profile_modules FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_profile_modules_select
ON public.tenant_profile_modules
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_profile = tenant_profile_modules.id_profile
      AND public.is_active_tenant_member(tp.id_tenant)
  )
);

CREATE POLICY tenant_profile_modules_insert
ON public.tenant_profile_modules
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_profile = tenant_profile_modules.id_profile
      AND public.has_tenant_role(
        tp.id_tenant,
        ARRAY['OWNER', 'ADMIN']::TEXT[]
      )
  )
);

CREATE POLICY tenant_profile_modules_update
ON public.tenant_profile_modules
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_profile = tenant_profile_modules.id_profile
      AND public.has_tenant_role(
        tp.id_tenant,
        ARRAY['OWNER', 'ADMIN']::TEXT[]
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_profile = tenant_profile_modules.id_profile
      AND public.has_tenant_role(
        tp.id_tenant,
        ARRAY['OWNER', 'ADMIN']::TEXT[]
      )
  )
);

CREATE POLICY tenant_profile_modules_delete
ON public.tenant_profile_modules
FOR DELETE
USING (
  EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_profile = tenant_profile_modules.id_profile
      AND public.has_tenant_role(
        tp.id_tenant,
        ARRAY['OWNER', 'ADMIN']::TEXT[]
      )
  )
);


-- -----------------------------------------------------------------------------
-- 11.5. TENANT_INVITATIONS
-- -----------------------------------------------------------------------------

ALTER TABLE public.tenant_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_invitations FORCE ROW LEVEL SECURITY;

-- OWNER y ADMIN pueden consultar las invitaciones del tenant.
-- El destinatario también puede consultar invitaciones correspondientes a su
-- propio correo verificado.
CREATE POLICY tenant_invitations_select
ON public.tenant_invitations
FOR SELECT
USING (
  public.has_tenant_role(
    id_tenant,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  )
  OR public.is_current_user_verified_email(email)
);





ALTER TABLE public.personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personas FORCE ROW LEVEL SECURITY;

CREATE POLICY personas_policy ON personas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.persona_condiciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.persona_condiciones FORCE ROW LEVEL SECURITY;

CREATE POLICY persona_condiciones_policy ON public.persona_condiciones
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.terrenos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terrenos FORCE ROW LEVEL SECURITY;

CREATE POLICY terrenos_policy ON public.terrenos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.juntas_directivas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.juntas_directivas FORCE ROW LEVEL SECURITY;

CREATE POLICY juntas_directivas_policy ON public.juntas_directivas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);



ALTER TABLE public.faenas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faenas FORCE ROW LEVEL SECURITY;

CREATE POLICY faenas_policy ON public.faenas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.asambleas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asambleas FORCE ROW LEVEL SECURITY;

CREATE POLICY asambleas_policy ON public.asambleas
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.bienes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bienes FORCE ROW LEVEL SECURITY;

CREATE POLICY bienes_policy ON public.bienes
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.persona_terreno ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.persona_terreno FORCE ROW LEVEL SECURITY;

CREATE POLICY persona_terreno_policy ON public.persona_terreno
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.junta_miembros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.junta_miembros FORCE ROW LEVEL SECURITY;

CREATE POLICY junta_miembros_policy ON public.junta_miembros
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.faena_participacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faena_participacion FORCE ROW LEVEL SECURITY;

CREATE POLICY faena_participacion_policy ON public.faena_participacion
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.asistencia_asamblea ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencia_asamblea FORCE ROW LEVEL SECURITY;

CREATE POLICY asistencia_asamblea_policy ON public.asistencia_asamblea
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.caja_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caja_categorias FORCE ROW LEVEL SECURITY;

CREATE POLICY caja_categorias_policy ON public.caja_categorias
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.caja_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caja_movimientos FORCE ROW LEVEL SECURITY;

CREATE POLICY caja_movimientos_policy ON public.caja_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.conceptos_cobro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conceptos_cobro FORCE ROW LEVEL SECURITY;

CREATE POLICY conceptos_cobro_policy ON public.conceptos_cobro
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.obligaciones_persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obligaciones_persona FORCE ROW LEVEL SECURITY;

CREATE POLICY obligaciones_persona_policy ON obligaciones_persona
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.obligacion_pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obligacion_pagos FORCE ROW LEVEL SECURITY;

CREATE POLICY obligacion_pagos_policy ON public.obligacion_pagos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.obligacion_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obligacion_movimientos FORCE ROW LEVEL SECURITY;

CREATE POLICY obligacion_movimientos_policy ON public.obligacion_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.creditos_persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creditos_persona FORCE ROW LEVEL SECURITY;

CREATE POLICY creditos_persona_policy ON public.creditos_persona
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


ALTER TABLE public.credito_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credito_movimientos FORCE ROW LEVEL SECURITY;

CREATE POLICY credito_movimientos_policy ON public.credito_movimientos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);



ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentos FORCE ROW LEVEL SECURITY;

CREATE POLICY documentos_policy ON documentos
USING (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);






ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log FORCE ROW LEVEL SECURITY;

CREATE POLICY audit_log_policy ON public.audit_log
USING (
  id_tenant IS NOT NULL
  AND id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
)
WITH CHECK (
  id_tenant IS NOT NULL
  AND id_tenant = current_setting('app.tenant_id', true)::bigint
  AND public.is_active_tenant_member(id_tenant)
);


-- Las escrituras se realizan mediante funciones controladas.

-- =============================================================================
-- 12. OPERACIONES SEGURAS DEL DOMINIO
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 12.1. CREAR TENANT Y REGISTRAR AL OWNER
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_tenant(
  p_nombre             VARCHAR,
  p_tipo_documento     VARCHAR DEFAULT NULL,
  p_numero_documento   VARCHAR DEFAULT NULL,
  p_observaciones      VARCHAR DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id   BIGINT;
  v_tenant_id BIGINT;
BEGIN
  v_user_id := public.app_current_user_id();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.auth_users au
    WHERE au.id_user = v_user_id
      AND au.estado = 'ACTIVO'
      AND au.email_verified = TRUE
  ) THEN
    RAISE EXCEPTION 'El usuario debe estar activo y tener el correo verificado';
  END IF;

  IF NULLIF(btrim(p_nombre), '') IS NULL THEN
    RAISE EXCEPTION 'El nombre del tenant es obligatorio';
  END IF;

  INSERT INTO public.tenants (
    nombre,
    tipo_documento,
    numero_documento,
    observaciones
  )
  VALUES (
    btrim(p_nombre),
    NULLIF(btrim(p_tipo_documento), ''),
    NULLIF(btrim(p_numero_documento), ''),
    NULLIF(btrim(p_observaciones), '')
  )
  RETURNING id_tenant INTO v_tenant_id;

  INSERT INTO public.tenant_users (
    id_tenant,
    id_user,
    role,
    estado,
    joined_at,
    invited_by
  )
  VALUES (
    v_tenant_id,
    v_user_id,
    'OWNER',
    'ACTIVO',
    now(),
    NULL
  );

  RETURN v_tenant_id;
END;
$$;

ALTER FUNCTION public.create_tenant(VARCHAR, VARCHAR, VARCHAR, VARCHAR)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.create_tenant(VARCHAR, VARCHAR, VARCHAR, VARCHAR)
  FROM PUBLIC;


-- =============================================================================
-- ENVIAR TENANT A PAPELERA
-- =============================================================================

CREATE OR REPLACE FUNCTION public.enviar_tenant_a_papelera(
  p_tenant_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF public.app_current_user_id() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF NOT public.has_tenant_role(
    p_tenant_id,
    ARRAY['OWNER']::TEXT[]
  ) THEN
    RAISE EXCEPTION
      'Solamente el OWNER puede enviar el tenant a la papelera';
  END IF;

  UPDATE public.tenants
  SET estado = 'INACTIVO',
      deleted_at = now(),
      updated_at = now()
  WHERE id_tenant = p_tenant_id
    AND estado = 'ACTIVO'
    AND deleted_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'El tenant no existe, no está ACTIVO o ya fue enviado a la papelera';
  END IF;
END;
$$;

ALTER FUNCTION public.enviar_tenant_a_papelera(BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL
ON FUNCTION public.enviar_tenant_a_papelera(BIGINT)
FROM PUBLIC;

-- =============================================================================
-- RESTAURAR TENANT
-- =============================================================================

CREATE OR REPLACE FUNCTION public.restaurar_tenant(
  p_tenant_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF public.app_current_user_id() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF NOT public.has_tenant_role(
    p_tenant_id,
    ARRAY['OWNER']::TEXT[]
  ) THEN
    RAISE EXCEPTION
      'Solamente el OWNER puede restaurar el tenant';
  END IF;

  UPDATE public.tenants
  SET estado = 'ACTIVO',
      deleted_at = NULL,
      updated_at = now()
  WHERE id_tenant = p_tenant_id
    AND estado = 'INACTIVO'
    AND deleted_at IS NOT NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'El tenant no existe o no se encuentra en la papelera';
  END IF;
END;
$$;

ALTER FUNCTION public.restaurar_tenant(BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL
ON FUNCTION public.restaurar_tenant(BIGINT)
FROM PUBLIC;


-- =============================================================================
-- ELIMINAR TENANT DEFINITIVAMENTE
-- =============================================================================

CREATE OR REPLACE FUNCTION public.eliminar_tenant_definitivamente(
  p_tenant_id BIGINT,
  p_confirmacion VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF public.app_current_user_id() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF p_confirmacion <> 'ELIMINAR DEFINITIVAMENTE' THEN
    RAISE EXCEPTION 'La confirmación no es válida';
  END IF;

  IF NOT public.has_tenant_role(
    p_tenant_id,
    ARRAY['OWNER']::TEXT[]
  ) THEN
    RAISE EXCEPTION
      'Solamente el OWNER puede eliminar el tenant';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tenants t
    WHERE t.id_tenant = p_tenant_id
      AND t.estado = 'INACTIVO'
      AND t.deleted_at IS NOT NULL
  ) THEN
    RAISE EXCEPTION
      'El tenant debe estar en la papelera antes de eliminarse';
  END IF;

  DELETE FROM public.documentos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.audit_log
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.tenant_invitations
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.tenant_users
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.credito_movimientos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.creditos_persona
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.obligacion_pagos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.obligacion_movimientos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.obligaciones_persona
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.conceptos_cobro
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.caja_movimientos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.caja_categorias
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.faena_participacion
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.asistencia_asamblea
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.junta_miembros
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.persona_terreno
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.persona_condiciones
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.faenas
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.asambleas
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.juntas_directivas
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.terrenos
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.bienes
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.personas
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.tenant_profiles
  WHERE id_tenant = p_tenant_id;

  DELETE FROM public.tenants
  WHERE id_tenant = p_tenant_id;
END;
$$;

ALTER FUNCTION public.eliminar_tenant_definitivamente(BIGINT, VARCHAR)
  OWNER TO juntas_rls_definer;

REVOKE ALL
ON FUNCTION public.eliminar_tenant_definitivamente(BIGINT, VARCHAR)
FROM PUBLIC;

-- -----------------------------------------------------------------------------
-- 12.2. CREAR INVITACIÓN
-- -----------------------------------------------------------------------------
--
-- Devuelve el token en texto plano una sola vez. La BD almacena únicamente su
-- hash SHA-256. El backend debe enviar el token al destinatario y no registrarlo
-- en logs.

CREATE OR REPLACE FUNCTION public.create_tenant_invitation(
  p_tenant_id          BIGINT,
  p_email              CITEXT,
  p_role               VARCHAR DEFAULT 'MEMBER',
  p_id_profile         BIGINT DEFAULT NULL,
  p_expires_in_days    INTEGER DEFAULT 7,
  p_message            VARCHAR DEFAULT NULL
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id    BIGINT;
  v_email      CITEXT;
  v_token      TEXT;
  v_token_hash TEXT;
BEGIN
  v_user_id := public.app_current_user_id();
  v_email := NULLIF(btrim(p_email::TEXT), '')::CITEXT;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF NOT public.has_tenant_role(
    p_tenant_id,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  ) THEN
    RAISE EXCEPTION 'No tiene permiso para invitar usuarios a este tenant';
  END IF;

  IF v_email IS NULL THEN
    RAISE EXCEPTION 'El correo de invitación es obligatorio';
  END IF;

  IF p_role NOT IN ('ADMIN', 'MEMBER') THEN
    RAISE EXCEPTION 'El rol de la invitación debe ser ADMIN o MEMBER';
  END IF;

  IF p_expires_in_days < 1 OR p_expires_in_days > 30 THEN
    RAISE EXCEPTION 'La vigencia debe estar entre 1 y 30 días';
  END IF;

  IF p_id_profile IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_tenant = p_tenant_id
      AND tp.id_profile = p_id_profile
      AND tp.estado = TRUE
  ) THEN
    RAISE EXCEPTION 'El perfil no existe, está inactivo o pertenece a otro tenant';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.tenant_users tu
    JOIN public.auth_users au ON au.id_user = tu.id_user
    WHERE tu.id_tenant = p_tenant_id
      AND tu.estado = 'ACTIVO'
      AND au.email = v_email
  ) THEN
    RAISE EXCEPTION 'El usuario ya es miembro activo del tenant';
  END IF;

  v_token := encode(gen_random_bytes(32), 'hex');
  v_token_hash := encode(digest(v_token, 'sha256'), 'hex');

  INSERT INTO public.tenant_invitations (
    id_tenant,
    email,
    role,
    id_profile,
    token_hash,
    status,
    expires_at,
    invited_by,
    message
  )
  VALUES (
    p_tenant_id,
    v_email,
    p_role,
    p_id_profile,
    v_token_hash,
    'PENDING',
    now() + make_interval(days => p_expires_in_days),
    v_user_id,
    NULLIF(btrim(p_message), '')
  );

  RETURN v_token;
END;
$$;

ALTER FUNCTION public.create_tenant_invitation(
  BIGINT, CITEXT, VARCHAR, BIGINT, INTEGER, VARCHAR
) OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.create_tenant_invitation(
  BIGINT, CITEXT, VARCHAR, BIGINT, INTEGER, VARCHAR
) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.3. ACEPTAR INVITACIÓN
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.accept_tenant_invitation(
  p_token TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id       BIGINT;
  v_user_email    CITEXT;
  v_token_hash    TEXT;
  v_invitation    public.tenant_invitations%ROWTYPE;
BEGIN
  v_user_id := public.app_current_user_id();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  SELECT au.email
  INTO v_user_email
  FROM public.auth_users au
  WHERE au.id_user = v_user_id
    AND au.estado = 'ACTIVO'
    AND au.email_verified = TRUE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El usuario debe estar activo y tener el correo verificado';
  END IF;

  IF NULLIF(btrim(p_token), '') IS NULL THEN
    RAISE EXCEPTION 'El token es obligatorio';
  END IF;

  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  SELECT ti.*
  INTO v_invitation
  FROM public.tenant_invitations ti
  WHERE ti.token_hash = v_token_hash
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitación no encontrada';
  END IF;

  IF v_invitation.status <> 'PENDING' THEN
    RAISE EXCEPTION 'La invitación ya no está disponible';
  END IF;

  IF v_invitation.expires_at <= now() THEN
    UPDATE public.tenant_invitations
    SET status = 'EXPIRED'
    WHERE id_invitation = v_invitation.id_invitation;

    RAISE EXCEPTION 'La invitación ha expirado';
  END IF;

  IF v_invitation.email <> v_user_email THEN
    RAISE EXCEPTION 'La invitación corresponde a otro correo electrónico';
  END IF;

  INSERT INTO public.tenant_users (
    id_tenant,
    id_user,
    role,
    estado,
    joined_at,
    ended_at,
    invited_by,
    id_profile
  )
  VALUES (
    v_invitation.id_tenant,
    v_user_id,
    v_invitation.role,
    'ACTIVO',
    now(),
    NULL,
    v_invitation.invited_by,
    v_invitation.id_profile
  )
  ON CONFLICT (id_tenant, id_user)
  DO UPDATE
  SET role = EXCLUDED.role,
      estado = 'ACTIVO',
      joined_at = now(),
      ended_at = NULL,
      invited_by = EXCLUDED.invited_by,
      id_profile = EXCLUDED.id_profile;

  UPDATE public.tenant_invitations
  SET status = 'ACCEPTED',
      accepted_at = now()
  WHERE id_invitation = v_invitation.id_invitation;

  RETURN v_invitation.id_tenant;
END;
$$;

ALTER FUNCTION public.accept_tenant_invitation(TEXT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.accept_tenant_invitation(TEXT) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.4. RECHAZAR INVITACIÓN
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.reject_tenant_invitation(
  p_token TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id       BIGINT;
  v_user_email    CITEXT;
  v_token_hash    TEXT;
  v_invitation    public.tenant_invitations%ROWTYPE;
BEGIN
  v_user_id := public.app_current_user_id();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  SELECT au.email
  INTO v_user_email
  FROM public.auth_users au
  WHERE au.id_user = v_user_id
    AND au.estado = 'ACTIVO'
    AND au.email_verified = TRUE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El usuario debe estar activo y tener el correo verificado';
  END IF;

  v_token_hash := encode(digest(p_token, 'sha256'), 'hex');

  SELECT ti.*
  INTO v_invitation
  FROM public.tenant_invitations ti
  WHERE ti.token_hash = v_token_hash
  FOR UPDATE;

  IF NOT FOUND OR v_invitation.status <> 'PENDING' THEN
    RAISE EXCEPTION 'La invitación no está disponible';
  END IF;

  IF v_invitation.email <> v_user_email THEN
    RAISE EXCEPTION 'La invitación corresponde a otro correo electrónico';
  END IF;

  UPDATE public.tenant_invitations
  SET status = 'REJECTED',
      rejected_at = now()
  WHERE id_invitation = v_invitation.id_invitation;
END;
$$;

ALTER FUNCTION public.reject_tenant_invitation(TEXT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.reject_tenant_invitation(TEXT) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.5. REVOCAR INVITACIÓN
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.revoke_tenant_invitation(
  p_invitation_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_tenant_id BIGINT;
BEGIN
  SELECT ti.id_tenant
  INTO v_tenant_id
  FROM public.tenant_invitations ti
  WHERE ti.id_invitation = p_invitation_id
    AND ti.status = 'PENDING'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitación pendiente no encontrada';
  END IF;

  IF NOT public.has_tenant_role(
    v_tenant_id,
    ARRAY['OWNER', 'ADMIN']::TEXT[]
  ) THEN
    RAISE EXCEPTION 'No tiene permiso para revocar esta invitación';
  END IF;

  UPDATE public.tenant_invitations
  SET status = 'REVOKED',
      revoked_at = now()
  WHERE id_invitation = p_invitation_id;
END;
$$;

ALTER FUNCTION public.revoke_tenant_invitation(BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.revoke_tenant_invitation(BIGINT) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.6. CAMBIAR ROL O PERFIL DE UN MIEMBRO
-- -----------------------------------------------------------------------------
--
-- OWNER puede modificar ADMIN y MEMBER.
-- ADMIN solo puede modificar miembros MEMBER y no puede asignar OWNER/ADMIN.

CREATE OR REPLACE FUNCTION public.update_tenant_member(
  p_tenant_id          BIGINT,
  p_member_user_id     BIGINT,
  p_new_role           VARCHAR,
  p_new_profile_id     BIGINT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_actor_id           BIGINT;
  v_actor_role         VARCHAR(15);
  v_current_role       VARCHAR(15);
BEGIN
  v_actor_id := public.app_current_user_id();

  SELECT tu.role
  INTO v_actor_role
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
    AND tu.id_user = v_actor_id
    AND tu.estado = 'ACTIVO';

  IF NOT FOUND OR v_actor_role NOT IN ('OWNER', 'ADMIN') THEN
    RAISE EXCEPTION 'No tiene permiso para modificar miembros';
  END IF;

  SELECT tu.role
  INTO v_current_role
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
    AND tu.id_user = p_member_user_id
    AND tu.estado = 'ACTIVO'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El miembro activo no existe en el tenant';
  END IF;

  IF p_new_role NOT IN ('ADMIN', 'MEMBER') THEN
    RAISE EXCEPTION 'Use transfer_tenant_ownership para asignar el rol OWNER';
  END IF;

  IF v_current_role = 'OWNER' THEN
    RAISE EXCEPTION 'El OWNER no puede modificarse mediante esta función';
  END IF;

  IF v_actor_role = 'ADMIN' THEN
    IF v_current_role <> 'MEMBER' OR p_new_role <> 'MEMBER' THEN
      RAISE EXCEPTION 'Un ADMIN solo puede administrar miembros con rol MEMBER';
    END IF;
  END IF;

  IF p_new_profile_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.tenant_profiles tp
    WHERE tp.id_tenant = p_tenant_id
      AND tp.id_profile = p_new_profile_id
      AND tp.estado = TRUE
  ) THEN
    RAISE EXCEPTION 'El perfil no existe, está inactivo o pertenece a otro tenant';
  END IF;

  UPDATE public.tenant_users
  SET role = p_new_role,
      id_profile = p_new_profile_id
  WHERE id_tenant = p_tenant_id
    AND id_user = p_member_user_id;
END;
$$;

ALTER FUNCTION public.update_tenant_member(BIGINT, BIGINT, VARCHAR, BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.update_tenant_member(
  BIGINT, BIGINT, VARCHAR, BIGINT
) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.7. DESACTIVAR MIEMBRO
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.deactivate_tenant_member(
  p_tenant_id          BIGINT,
  p_member_user_id     BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_actor_id       BIGINT;
  v_actor_role     VARCHAR(15);
  v_member_role    VARCHAR(15);
BEGIN
  v_actor_id := public.app_current_user_id();

  SELECT tu.role
  INTO v_actor_role
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
    AND tu.id_user = v_actor_id
    AND tu.estado = 'ACTIVO';

  IF NOT FOUND OR v_actor_role NOT IN ('OWNER', 'ADMIN') THEN
    RAISE EXCEPTION 'No tiene permiso para retirar miembros';
  END IF;

  SELECT tu.role
  INTO v_member_role
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
    AND tu.id_user = p_member_user_id
    AND tu.estado = 'ACTIVO'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El miembro activo no existe en el tenant';
  END IF;

  IF v_member_role = 'OWNER' THEN
    RAISE EXCEPTION 'El OWNER debe transferir la propiedad antes de retirarse';
  END IF;

  IF v_actor_role = 'ADMIN' AND v_member_role <> 'MEMBER' THEN
    RAISE EXCEPTION 'Un ADMIN no puede retirar a otro ADMIN';
  END IF;

  UPDATE public.tenant_users
  SET estado = 'INACTIVO',
      ended_at = now()
  WHERE id_tenant = p_tenant_id
    AND id_user = p_member_user_id;
END;
$$;

ALTER FUNCTION public.deactivate_tenant_member(BIGINT, BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.deactivate_tenant_member(BIGINT, BIGINT)
  FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.8. ABANDONAR TENANT
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.leave_tenant(
  p_tenant_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id BIGINT;
  v_role    VARCHAR(15);
BEGIN
  v_user_id := public.app_current_user_id();

  SELECT tu.role
  INTO v_role
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
    AND tu.id_user = v_user_id
    AND tu.estado = 'ACTIVO'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No pertenece activamente al tenant';
  END IF;

  IF v_role = 'OWNER' THEN
    RAISE EXCEPTION 'El OWNER debe transferir la propiedad antes de abandonar el tenant';
  END IF;

  UPDATE public.tenant_users
  SET estado = 'INACTIVO',
      ended_at = now()
  WHERE id_tenant = p_tenant_id
    AND id_user = v_user_id;
END;
$$;

ALTER FUNCTION public.leave_tenant(BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.leave_tenant(BIGINT) FROM PUBLIC;


-- -----------------------------------------------------------------------------
-- 12.9. TRANSFERIR PROPIEDAD
-- -----------------------------------------------------------------------------
--
-- La operación es atómica. El OWNER actual pasa a ADMIN y el miembro indicado
-- se convierte en OWNER dentro de la misma transacción.

CREATE OR REPLACE FUNCTION public.transfer_tenant_ownership(
  p_tenant_id          BIGINT,
  p_new_owner_user_id  BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_current_owner_id BIGINT;
BEGIN
  v_current_owner_id := public.app_current_user_id();

  IF v_current_owner_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  -- Serializa cambios de membresía dentro del tenant.
  PERFORM 1
  FROM public.tenant_users tu
  WHERE tu.id_tenant = p_tenant_id
  ORDER BY tu.id_user
  FOR UPDATE;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tenant_users tu
    WHERE tu.id_tenant = p_tenant_id
      AND tu.id_user = v_current_owner_id
      AND tu.role = 'OWNER'
      AND tu.estado = 'ACTIVO'
  ) THEN
    RAISE EXCEPTION 'Solo el OWNER actual puede transferir la propiedad';
  END IF;

  IF p_new_owner_user_id = v_current_owner_id THEN
    RAISE EXCEPTION 'El usuario indicado ya es el OWNER';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tenant_users tu
    WHERE tu.id_tenant = p_tenant_id
      AND tu.id_user = p_new_owner_user_id
      AND tu.estado = 'ACTIVO'
  ) THEN
    RAISE EXCEPTION 'El nuevo OWNER debe ser miembro activo del tenant';
  END IF;

  UPDATE public.tenant_users
  SET role = 'ADMIN'
  WHERE id_tenant = p_tenant_id
    AND id_user = v_current_owner_id
    AND role = 'OWNER'
    AND estado = 'ACTIVO';

  UPDATE public.tenant_users
  SET role = 'OWNER'
  WHERE id_tenant = p_tenant_id
    AND id_user = p_new_owner_user_id
    AND estado = 'ACTIVO';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No fue posible establecer el nuevo OWNER';
  END IF;
END;
$$;

ALTER FUNCTION public.transfer_tenant_ownership(BIGINT, BIGINT)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.transfer_tenant_ownership(BIGINT, BIGINT)
  FROM PUBLIC;


-- =============================================================================
-- 13. PERMISOS PARA EL ROL DE LA APLICACIÓN
-- =============================================================================
--
-- Reemplazar app_authenticated por el rol real utilizado por el backend.
-- Estas sentencias están comentadas para no fallar si dicho rol todavía no existe.
--
-- La aplicación puede consultar las tablas protegidas por RLS, pero las
-- operaciones sensibles se ejecutan exclusivamente mediante funciones.

/*
GRANT USAGE ON SCHEMA public TO app_authenticated;

GRANT SELECT ON public.tenants TO app_authenticated;
GRANT SELECT ON public.tenant_users TO app_authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenant_profiles TO app_authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenant_profile_modules TO app_authenticated;
GRANT SELECT ON public.tenant_invitations TO app_authenticated;

GRANT EXECUTE ON FUNCTION public.is_active_tenant_member(BIGINT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.has_tenant_role(BIGINT, TEXT[])
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.is_current_user_verified_email(CITEXT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.create_tenant(VARCHAR, VARCHAR, VARCHAR, VARCHAR)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.create_tenant_invitation(
  BIGINT, CITEXT, VARCHAR, BIGINT, INTEGER, VARCHAR
) TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.accept_tenant_invitation(TEXT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.reject_tenant_invitation(TEXT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_tenant_invitation(BIGINT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.update_tenant_member(
  BIGINT, BIGINT, VARCHAR, BIGINT
) TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.deactivate_tenant_member(BIGINT, BIGINT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.leave_tenant(BIGINT)
  TO app_authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_tenant_ownership(BIGINT, BIGINT)
  TO app_authenticated;
*/


-- =============================================================================
-- 14. EJEMPLOS DE USO
-- =============================================================================
-- crear un usuario
/*
INSERT INTO public.auth_users (
    email,
    nombres,
    apellidos,
    password_hash,
    email_verified,
   email_verified_at
)
VALUES (
        'abel@hotmail.com',
        'Abel',
        'Clemente',
        crypt('123!', gen_salt('bf', 12)),
        true,
        now()
)
*/

/*
-- Simular usuario autenticado dentro de una transacción:
BEGIN;
SELECT set_config('app.user_id', '1', true);

-- Crear tenant y convertirse en OWNER:
SELECT public.create_tenant(
  'Junta Directiva Residencial Los Jardines',
  'RUC',
  '20123456789',
  'Tenant principal'
);
COMMIT;


-- Crear invitación. La función devuelve el token en texto plano una sola vez:
BEGIN;
SELECT set_config('app.user_id', '1', true);
SELECT public.create_tenant_invitation(
  1,
  'invitado@correo.com',
  'MEMBER',
  NULL,
  7,
  'Te invitamos a participar en nuestra junta directiva.'
);
COMMIT;


-- Aceptar invitación con el usuario destinatario:
BEGIN;
SELECT set_config('app.user_id', '2', true);
SELECT public.accept_tenant_invitation('TOKEN_RECIBIDO_POR_CORREO');
COMMIT;


-- Transferir propiedad:
BEGIN;
SELECT set_config('app.user_id', '1', true);
SELECT public.transfer_tenant_ownership(1, 2);
COMMIT;
*/
