/*
set app.user_id=1;
set app.tenant_id=7;
 */

insert into personas(ID_TENANT,nombres,apellidopaterno,apellidomaterno,tipo_participante,estado,fecha_registro)
values
(7,'Brisel Maria','Salas','Quispe','PADRONADO','ACTIVO',now()),
(7,'Felipe','Quispe','Durand','PADRONADO','ACTIVO',now()),
(7,'Ana','Acurio','Ramos','PADRONADO','ACTIVO',now()),
(7,'Saturnino','Amache','Amache','PADRONADO','ACTIVO',now()),
(7,'Guillermo','Nina','Huaman','PADRONADO','ACTIVO',now()),
(7,'Luis','Hurtado','Mendoza','PADRONADO','ACTIVO',now()),
(7,'Noe','Vega','Castro','PADRONADO','ACTIVO',now()),
(7,'Beatriz','Romero','Farfan','PADRONADO','ACTIVO',now()),
(7,'Nohemi','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Natividad','Mondaca','Chura','PADRONADO','ACTIVO',now()),
(7,'Agustin','Churata','Cuyuchi','PADRONADO','ACTIVO',now()),
(7,'Bacilio','Quehuarucho','Quispe','PADRONADO','ACTIVO',now()),
(7,'Francisca','Moscoso','Ccala','PADRONADO','ACTIVO',now()),
(7,'German','Charahuayta','Cespedes','PADRONADO','ACTIVO',now()),
(7,'Pedro','Huamani','Cayllahua','PADRONADO','ACTIVO',now()),
(7,'Cirila','Cordova','Sanchez','PADRONADO','ACTIVO',now()),
(7,'Julio Antonio','Acuna','Florez','PADRONADO','ACTIVO',now()),
(7,'Pedro','Ccahua','Borda','PADRONADO','ACTIVO',now()),
(7,'Hipolito Marter','Hilares','Hancco','PADRONADO','ACTIVO',now()),
(7,'Emilio','Alfaro','Cruz','PADRONADO','ACTIVO',now()),
(7,'Justino','Pena','Chuma','PADRONADO','ACTIVO',now()),
(7,'Lourdes','Jimenes','Cjuro','PADRONADO','ACTIVO',now()),
(7,'Victor','Kacha','Cjuro','PADRONADO','ACTIVO',now()),
(7,'Lily Carol','Carrillo','Yucra','PADRONADO','ACTIVO',now()),
(7,'Nicasio Paul','Llasa','Yucra','PADRONADO','ACTIVO',now()),
(7,'Eleuterio','Pila','Meza','PADRONADO','ACTIVO',now()),
(7,'Walter','Ata','Huillca','PADRONADO','ACTIVO',now()),
(7,'Edwin','Romero','Farfan','PADRONADO','ACTIVO',now()),
(7,'Alejandro','Cutire','Pazo','PADRONADO','ACTIVO',now()),
(7,'Jasmin Katherine','Cutucalla','Paz','PADRONADO','ACTIVO',now()),
(7,'Melchora','Quithua','Canari','PADRONADO','ACTIVO',now()),
(7,'Beniano','Montesinos','Pocorimay','PADRONADO','ACTIVO',now()),
(7,'Alicia','Ccallo','Maquerhua','PADRONADO','ACTIVO',now()),
(7,'Zenovia Constantina','Aymachoque','Tito','PADRONADO','ACTIVO',now()),
(7,'Nilo','Chavez','Vergara','PADRONADO','ACTIVO',now()),
(7,'Magdalena','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Julia','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Sonia','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Nelly Rossana','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Julio Cesar','Condori','Charalla','PADRONADO','ACTIVO',now()),
(7,'Wilber Braulio','Quillahuman','Rondan','PADRONADO','ACTIVO',now()),
(7,'Agripina','Miranda','Oreccón','PADRONADO','ACTIVO',now()),
(7,'Angela','Ccoto','Apaza','PADRONADO','ACTIVO',now()),
(7,'Denisse Elizabeth','Ferro','Montalvo','PADRONADO','ACTIVO',now()),
(7,'Melchora','Valer','Ramirez','PADRONADO','ACTIVO',now()),
(7,'Haydee','Furo','Marquez','PADRONADO','ACTIVO',now()),
(7,'Maritza','Calderon','Quispe','PADRONADO','ACTIVO',now()),
(7,'Simon','Vargas','Nina','PADRONADO','ACTIVO',now()),
(7,'Graceda','Alvarez','Apaza','PADRONADO','ACTIVO',now()),
(7,'Javier','Condori','Mollehuanca','PADRONADO','ACTIVO',now()),
(7,'Victor Luis','Mogollon','Villanueva','PADRONADO','ACTIVO',now()),
(7,'Primitiva','Gamarra','Aranya','PADRONADO','ACTIVO',now()),
(7,'Alejandro','Aranya','Mendoza','PADRONADO','ACTIVO',now()),
(7,'Victoria','Rocca','Lima','PADRONADO','ACTIVO',now()),
(7,'Dora','Valenzuela','Huarhua','PADRONADO','ACTIVO',now()),
(7,'David','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Marizol','Centeno','Chicilla','PADRONADO','ACTIVO',now()),
(7,'Gladis','Fernandez','Cardenas','PADRONADO','ACTIVO',now()),
(7,'Liseth Katia','Fuentes','Rios','PADRONADO','ACTIVO',now()),
(7,'Alejandro','Quispe','Huallpa','PADRONADO','ACTIVO',now()),
(7,'Edgar','Auccayse','Auccayse','PADRONADO','ACTIVO',now()),
(7,'Elias','Ccallo','Maquerhua','PADRONADO','ACTIVO',now()),
(7,'Rosa Silvia','Accostupa','Foranda','PADRONADO','ACTIVO',now()),
(7,'Benedicto','Guillen','Contreras','PADRONADO','ACTIVO',now()),
(7,'Biviana','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Hector','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Nancy','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Hipolito','Chata','Gonzales','PADRONADO','ACTIVO',now()),
(7,'Elias','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Hector','Quinones','Arce','PADRONADO','ACTIVO',now()),
(7,'Yoni','Quinones','Lopez','PADRONADO','ACTIVO',now()),
(7,'Jaime','Rojas','Cruz','PADRONADO','ACTIVO',now()),
(7,'Haydee','Perez','Alarcon','PADRONADO','ACTIVO',now()),
(7,'Nicomedes','Guillen','Contreras','PADRONADO','ACTIVO',now()),
(7,'Victoria','Guillen','Contreras','PADRONADO','ACTIVO',now()),
(7,'Francisco','Guillen','Contreras','PADRONADO','ACTIVO',now()),
(7,'Maria Luz','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Antonia','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Juan','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Renal Milton','Huillca','Guillen','PADRONADO','ACTIVO',now()),
(7,'Elizabeth','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Marina','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Cornelio','Guillen','Contreras','PADRONADO','ACTIVO',now()),
(7,'Mayda','Rugama','Aranya','PADRONADO','ACTIVO',now()),
(7,'Juan Junior','Guillen','Guisado','PADRONADO','ACTIVO',now()),
(7,'Celia','Chavez','Nahui','PADRONADO','ACTIVO',now()),
(7,'Nemesia','Pezo','Satta','PADRONADO','ACTIVO',now()),
(7,'Walter','Alvarez','Perez','PADRONADO','ACTIVO',now()),
(7,'Oscar','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Jose Angel','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Florentino','Guillen','Caballero','PADRONADO','ACTIVO',now()),
(7,'Marlene Susana','Guillen','Aquise','PADRONADO','ACTIVO',now()),
(7,'Maria Magdalena','Papel','Quispe','PADRONADO','ACTIVO',now()),
(7,'Buenaventura','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Miguel','Farfan','Huillca','PADRONADO','ACTIVO',now()),
(7,'Alcione','Huaman','Llancay','PADRONADO','ACTIVO',now()),
(7,'Felicitas','Gomez','Huaman','PADRONADO','ACTIVO',now()),
(7,'Virgilio','Gomez','Huaman','PADRONADO','ACTIVO',now()),
(7,'Nancy','Alfaro','Percca','PADRONADO','ACTIVO',now()),
(7,'Cayetano','Gutierrez','Coahuana','PADRONADO','ACTIVO',now()),
(7,'Hilda','Yupangui','Tito','PADRONADO','ACTIVO',now()),
(7,'Vistor','Ocampo','Altamirano','PADRONADO','ACTIVO',now()),
(7,'Yeni V','Ampuero','Villanueva','PADRONADO','ACTIVO',now()),
(7,'Raymundo','Leva','Ccuno','PADRONADO','ACTIVO',now()),
(7,'Walter','Kallafranco','Huillca','PADRONADO','ACTIVO',now()),
(7,'Nestor Ysaac','Matias','Bonifacio','PADRONADO','ACTIVO',now()),
(7,'Delia','Cjuno','Chinchercoma','PADRONADO','ACTIVO',now()),
(7,'Tito','Guillen','Carahuaringa','PADRONADO','ACTIVO',now()),
(7,'Simeon','Hurtado','Aguirre','PADRONADO','ACTIVO',now()),
(7,'Rocio','Almiron','Quispe','PADRONADO','ACTIVO',now()),
(7,'Katherin','Valer','Moscoso','PADRONADO','ACTIVO',now()),
(7,'Nelly','Kachahualpa','Huillca','PADRONADO','ACTIVO',now()),
(7,'Silvia','Cjuno','Chinchercoma','PADRONADO','ACTIVO',now()),
(7,'Juana','Callapina','Aranya','PADRONADO','ACTIVO',now()),
(7,'Karina','Blanco','Huayllapuma','PADRONADO','ACTIVO',now()),
(7,'Maritza','Pure','Bocangel','PADRONADO','ACTIVO',now()),
(7,'David','Ocampo','Altamirano','PADRONADO','ACTIVO',now()),
(7,'Rosario','Bellido','Ccoto','PADRONADO','ACTIVO',now()),
(7,'Claudio','Bellido','Ccoto','PADRONADO','ACTIVO',now()),
(7,'Antonia','Callapina','Aranya','PADRONADO','ACTIVO',now()),
(7,'Milagros Pilar','Poncca','Callapina','PADRONADO','ACTIVO',now()),
(7,'Bernardina','Bellido','Ccoto','PADRONADO','ACTIVO',now()),
(7,'Antolina','Bellido','Ccoto','PADRONADO','ACTIVO',now()),
(7,'Leonor Alendra','Oviedo','Bejar','PADRONADO','ACTIVO',now()),
(7,'Dora Isabel','Monzon','Duenas','PADRONADO','ACTIVO',now()),
(7,'Marisol','Chahua','Quispe','PADRONADO','ACTIVO',now()),
(7,'Nataly','Pumachara','Pila','PADRONADO','ACTIVO',now()),
(7,'Julia','Quispe','Mainiata','PADRONADO','ACTIVO',now()),
(7,'Oscar Abel','Clemente','Taco','PADRONADO','ACTIVO',now()),
(7,'Eulogia','Lopez','Carbajal','PADRONADO','ACTIVO',now()),
(7,'Marleny','Chahua','Quispe','PADRONADO','ACTIVO',now()),
(7,'Enrriqueta','Quispe','Chaucca','PADRONADO','ACTIVO',now()),
(7,'Nelly','Antezana','Barreda','PADRONADO','ACTIVO',now()),
(7,'Jhon','Luque','Calderon','PADRONADO','ACTIVO',now()),
(7,'Norma','Gonzales','Gonzales','PADRONADO','ACTIVO',now()),
(7,'Ruben','Huallpayunca','Gutierrez','PADRONADO','ACTIVO',now()),
(7,'Margarita','Gutierrez','Gutierrez','PADRONADO','ACTIVO',now()),
(7,'Yeny','Ayala','Luque','PADRONADO','ACTIVO',now()),
(7,'Juan','Huamani','Monzon','PADRONADO','ACTIVO',now()),
(7,'Hilda','Charalla','Merma','PADRONADO','ACTIVO',now()),
(7,'Hernan','Usca','Chino','PADRONADO','ACTIVO',now()),
(7,'Ramon','Huacasi','Huacasi','PADRONADO','ACTIVO',now()),
(7,'Hilda','Puyo','Quispe','PADRONADO','ACTIVO',now()),
(7,'Galinverty','Bolivar','Bolivar','PADRONADO','ACTIVO',now()),
(7,'Juan','Uscapi','Mamani','PADRONADO','ACTIVO',now()),
(7,'Grimaldo','Guillen','Caceres','PADRONADO','ACTIVO',now()),
(7,'Justino','Pena','Pena','PADRONADO','ACTIVO',now()),
(7,'Jesus','Hualpa','Mendoza','PADRONADO','ACTIVO',now());