BEGIN;

CREATE TABLE IF NOT EXISTS public.persona_constancias (
  id_constancia      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_tenant          BIGINT NOT NULL,
  id_persona         BIGINT NOT NULL,
  codigo             VARCHAR(32) NOT NULL,
  token_hash         VARCHAR(64) NOT NULL,
  snapshot           JSONB NOT NULL,
  snapshot_hash      VARCHAR(64) NOT NULL,
  issued_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  issued_by_user     BIGINT NOT NULL,
  revoked_at         TIMESTAMPTZ NULL,
  revoked_by_user    BIGINT NULL,
  motivo_revocacion  VARCHAR(300) NULL,

  CONSTRAINT pk_persona_constancias PRIMARY KEY (id_constancia),
  CONSTRAINT uq_persona_constancias_tenant_constancia UNIQUE (id_tenant, id_constancia),
  CONSTRAINT ux_persona_constancias_codigo UNIQUE (codigo),
  CONSTRAINT ux_persona_constancias_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_persona_constancias_tenant
    FOREIGN KEY (id_tenant) REFERENCES public.tenants (id_tenant) ON DELETE CASCADE,
  CONSTRAINT fk_persona_constancias_persona
    FOREIGN KEY (id_tenant, id_persona)
    REFERENCES public.personas (id_tenant, id_persona) ON DELETE CASCADE,
  CONSTRAINT fk_persona_constancias_issued_by
    FOREIGN KEY (issued_by_user) REFERENCES public.auth_users (id_user),
  CONSTRAINT fk_persona_constancias_revoked_by
    FOREIGN KEY (revoked_by_user) REFERENCES public.auth_users (id_user),
  CONSTRAINT ck_persona_constancias_revocacion CHECK (
    (revoked_at IS NULL AND revoked_by_user IS NULL AND motivo_revocacion IS NULL)
    OR
    (revoked_at IS NOT NULL AND revoked_by_user IS NOT NULL AND motivo_revocacion IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS ix_persona_constancias_persona
  ON public.persona_constancias (id_tenant, id_persona, issued_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.persona_constancias TO juntas_rls_definer;
GRANT USAGE, SELECT ON SEQUENCE public.persona_constancias_id_constancia_seq TO juntas_rls_definer;
REVOKE INSERT, UPDATE, DELETE ON public.persona_constancias FROM juntas_backend;

ALTER TABLE public.persona_constancias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.persona_constancias FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS persona_constancias_select ON public.persona_constancias;
CREATE POLICY persona_constancias_select ON public.persona_constancias
FOR SELECT
USING (
  id_tenant = public.app_current_tenant_id()
  AND public.can_access_active_tenant(id_tenant)
);

DROP POLICY IF EXISTS persona_constancias_insert ON public.persona_constancias;
CREATE POLICY persona_constancias_insert ON public.persona_constancias
FOR INSERT
WITH CHECK (
  id_tenant = public.app_current_tenant_id()
  AND public.can_admin_active_tenant(id_tenant)
  AND issued_by_user = public.app_current_user_id()
);

DROP POLICY IF EXISTS persona_constancias_update ON public.persona_constancias;
CREATE POLICY persona_constancias_update ON public.persona_constancias
FOR UPDATE
USING (
  id_tenant = public.app_current_tenant_id()
  AND public.can_admin_active_tenant(id_tenant)
)
WITH CHECK (
  id_tenant = public.app_current_tenant_id()
  AND public.can_admin_active_tenant(id_tenant)
);

CREATE OR REPLACE FUNCTION public.fn_emitir_persona_constancia(
  p_tenant_id BIGINT,
  p_persona_id BIGINT,
  p_codigo VARCHAR,
  p_token_hash VARCHAR,
  p_snapshot JSONB,
  p_snapshot_hash VARCHAR
)
RETURNS TABLE (id_constancia BIGINT, issued_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id BIGINT;
BEGIN
  v_user_id := public.app_current_user_id();

  IF v_user_id IS NULL OR public.app_current_tenant_id() IS DISTINCT FROM p_tenant_id THEN
    RAISE EXCEPTION 'Falta contexto de tenant o usuario para emitir la constancia';
  END IF;

  IF NOT public.can_admin_active_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'No tiene permisos para emitir constancias';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.personas p
    WHERE p.id_tenant = p_tenant_id AND p.id_persona = p_persona_id
  ) THEN
    RAISE EXCEPTION 'La persona no existe en el tenant activo';
  END IF;

  RETURN QUERY
  INSERT INTO public.persona_constancias (
    id_tenant, id_persona, codigo, token_hash, snapshot, snapshot_hash, issued_by_user
  )
  VALUES (
    p_tenant_id,
    p_persona_id,
    NULLIF(btrim(p_codigo), ''),
    NULLIF(btrim(p_token_hash), ''),
    p_snapshot,
    NULLIF(btrim(p_snapshot_hash), ''),
    v_user_id
  )
  RETURNING persona_constancias.id_constancia, persona_constancias.issued_at;
END;
$$;

ALTER FUNCTION public.fn_emitir_persona_constancia(BIGINT, BIGINT, VARCHAR, VARCHAR, JSONB, VARCHAR)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.fn_emitir_persona_constancia(BIGINT, BIGINT, VARCHAR, VARCHAR, JSONB, VARCHAR)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_emitir_persona_constancia(BIGINT, BIGINT, VARCHAR, VARCHAR, JSONB, VARCHAR)
  TO juntas_backend;

CREATE OR REPLACE FUNCTION public.fn_revocar_persona_constancia(
  p_tenant_id BIGINT,
  p_persona_id BIGINT,
  p_constancia_id BIGINT,
  p_motivo VARCHAR
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id BIGINT;
  v_constancia_id BIGINT;
BEGIN
  v_user_id := public.app_current_user_id();

  IF v_user_id IS NULL OR public.app_current_tenant_id() IS DISTINCT FROM p_tenant_id THEN
    RAISE EXCEPTION 'Falta contexto de tenant o usuario para revocar la constancia';
  END IF;

  IF NOT public.can_admin_active_tenant(p_tenant_id) THEN
    RAISE EXCEPTION 'No tiene permisos para revocar constancias';
  END IF;

  UPDATE public.persona_constancias
  SET revoked_at = now(),
      revoked_by_user = v_user_id,
      motivo_revocacion = NULLIF(btrim(p_motivo), '')
  WHERE id_constancia = p_constancia_id
    AND id_tenant = p_tenant_id
    AND id_persona = p_persona_id
    AND revoked_at IS NULL
  RETURNING id_constancia INTO v_constancia_id;

  RETURN v_constancia_id;
END;
$$;

ALTER FUNCTION public.fn_revocar_persona_constancia(BIGINT, BIGINT, BIGINT, VARCHAR)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.fn_revocar_persona_constancia(BIGINT, BIGINT, BIGINT, VARCHAR)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_revocar_persona_constancia(BIGINT, BIGINT, BIGINT, VARCHAR)
  TO juntas_backend;

CREATE OR REPLACE FUNCTION public.fn_verificar_persona_constancia(
  p_token_hash VARCHAR
)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT jsonb_build_object(
    'valida', pc.revoked_at IS NULL,
    'estado', CASE WHEN pc.revoked_at IS NULL THEN 'VIGENTE' ELSE 'REVOCADA' END,
    'codigo', pc.codigo,
    'issuedAt', pc.issued_at,
    'revokedAt', pc.revoked_at,
    'motivoRevocacion', pc.motivo_revocacion,
    'tenant', jsonb_build_object(
      'nombre', pc.snapshot #>> '{tenant,nombre}',
      'tipoDocumento', pc.snapshot #>> '{tenant,tipoDocumento}',
      'numeroDocumento', pc.snapshot #>> '{tenant,numeroDocumento}'
    ),
    'persona', jsonb_build_object(
      'nombreCompleto', pc.snapshot #>> '{persona,nombreCompleto}',
      'dniEnmascarado', CASE
        WHEN NULLIF(pc.snapshot #>> '{persona,dni}', '') IS NULL THEN NULL
        WHEN length(pc.snapshot #>> '{persona,dni}') <= 4
          THEN repeat('*', length(pc.snapshot #>> '{persona,dni}'))
        ELSE repeat('*', length(pc.snapshot #>> '{persona,dni}') - 4)
          || right(pc.snapshot #>> '{persona,dni}', 4)
      END,
      'nroPadron', pc.snapshot #> '{persona,nroPadron}',
      'estado', pc.snapshot #>> '{persona,estado}'
    ),
    'snapshotHash', pc.snapshot_hash
  )
  FROM public.persona_constancias pc
  WHERE pc.token_hash = NULLIF(btrim(p_token_hash), '')
  LIMIT 1;
$$;

ALTER FUNCTION public.fn_verificar_persona_constancia(VARCHAR)
  OWNER TO juntas_rls_definer;

REVOKE ALL ON FUNCTION public.fn_verificar_persona_constancia(VARCHAR)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_verificar_persona_constancia(VARCHAR)
  TO juntas_backend;

COMMIT;
